### ISSUE TITLE
Request new ver release

### ISSUE THREAD

**Issue by oskCom** [electron/electron-rebuild#1001]
The build failed with an error in the combination of "Electron v17.2.0" and "electron-rebuild v3.2.7".
(This is the same problem as #994 )

However, the build will succeed with the combination of "Electron v17.2.0" and "electron-rebuild  latest master".

I think this problem has already been fixed.
Could you please release a new version ?

**Comment by MarshallOfSound** [comment]
You simply need to ensure that `node-abi` is up to date.  If you use yarn you can use `npx uuaw node-abi`.  If not you could manually fix this by removing `electron-rebuild`, running `npm install` then adding it back again and running `npm install`
