### ISSUE TITLE
about the version with electron

### ISSUE THREAD

**Issue by dfsq1311** [electron/electron-rebuild#101]
hello master,

when I use npm-pre-gyp to build the binary module,

the command usually is `node-pre-gyp install --fallback-to-build  --runtime=electron --target=1.3.3`,

1.3.3 is later than electron-rebuild release version,

so, I can't use electron@^1.3.3?

and just the version before 1.2.0 can be used?

**Comment by MarshallOfSound** [comment]
`electron-rebuild` and `electron` version are independent.  Electron rebuild works with all electron versions

**Comment by dfsq1311** [comment]
thanks
