### ISSUE TITLE
Could not detect abi for version 19.0.5 and runtime electron.

### ISSUE THREAD

**Issue by logidelic** [electron/electron-rebuild#1020]
Currently getting this error with electron-rebuild 3.2.7 & electron 19.0.5:

```
Could not detect abi for version 19.0.5 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```

**Comment by MarshallOfSound** [comment]
Have you followed the instructions and updated `node-abi`? If you're using `yarn` you can just do `npx uuaw node-abi` do update it deep
