### ISSUE TITLE
electron or mocha but not both

### ISSUE THREAD

**Issue by abulka** [electron/electron-rebuild#103]
Happily, running this wonderful tool `./node_modules/.bin/electron-rebuild` **works** for me on Mac and now I can finally `require` and use the npm [midi](https://www.npmjs.com/package/midi)  library in electron.  I **was** getting the dreaded _Module version mismatch. Expected 48, got 49_ issue.

However now, ironically, my Mocha tests now have the exact same Module version mismatch problem - they used to work!   I have Mocha installed locally and run them using `./node_modules/mocha/bin/mocha` and my mocha unit tests use that same midi library via. `var midi = require('midi');`.  

Yes, I can fix my Mocha problem by `rm -rf node_modules && npm install` and then the tests run - however then I'm back AT SQUARE ONE :) and I get the Module version mismatch problem in electron again!  

P.S. Its not just a mocha thing, its also reproducible by firing up node and typing `var midi = require('midi')`.

Can't I have my cake (mocha/regular node) and eat it (electron) too?  I do notice that the midi library has a `node-gyp rebuild` step.  Note that my node version is 6.3.0 and this is also the version that electron reports.

**Comment by MarshallOfSound** [comment]
@abulka This is due to mocha running in normal node and Electron running in wel.. Electron.

There is a wonderfully drop in solution to this issue.

Use [`electron-mocha`](https://github.com/jprichardson/electron-mocha)

It has exactly the same CLI interface as mocha but runs your tests inside a full Electron environment so your native modules will work.

Does this fulfill your requirements?

**Comment by abulka** [comment]
@MarshallOfSound That works and fixes my immediate problem, yes!  And thanks for the explanation that electron uses a secret special node build despite the fact that regular node and electron node report the same version number.

Of course if I were to be greedy, I'd also want to be able to import the npm midi library into my regular node e.g. for running various scripts and CLI experimentation.  But it sounds like you can only have one node-gyp compilation of that native library - so you have to choose - electron or regular node.  

Speculating out loud (I am a bit new to the node world): Somehow exposing "electron node" as the "regular" CLI node for a project would be cool.  I wonder if one of those node switching tools like [n](https://github.com/tj/n) could help do that.  Presumably that's not possible as it would have already been done and would arguably have been an even simpler solution to the problem that both electron-rebuild and electron-mocha solve.

**Comment by MarshallOfSound** [comment]
If you set the environment variable

```bash
export ELECTRON_RUN_AS_NODE=true
```

And then launch `electron` it will run exactly as if it was a normal `node` binary
