### ISSUE TITLE
Is there a quick way to undo electron-rebuild?

### ISSUE THREAD

**Issue by Petah** [electron/electron-rebuild#109]
Is there a quick way to undo electron-rebuild?

I currently have to run `electron-rebuild` to start my electron app (in dev mode/prebuilt). But when I package the app I have to `rm -rf node_modules && npm install && npm run dist`.

Is there a way I can make it so I don't need to do this? 

Im running:

```
$ node -v
v6.7.0
$ npm -v
3.10.8
$ ./node_modules/.bin/electron -v
v1.4.2
```

**Comment by paulcbetts** [comment]
Why would you have to do that unless you're using a different version of electron in dev vs production

**Comment by Petah** [comment]
Well Im not, at least that I know if.

```
$ npm ls | grep elec
├─┬ electron-builder@7.10.2
│ ├─┬ asar-electron-builder@0.13.5
│ ├─┬ electron-download@2.1.2
│ ├─┬ electron-osx-sign-tf@1.0.0
├─┬ electron-prebuilt@1.4.2
│ ├─┬ electron-download@3.0.1
├─┬ electron-rebuild@1.2.1
│ ├── electron-prebuilt@0.36.12
├─┬ grunt-electron-installer@2.1.0
│ └─┬ electron-winstaller@2.3.4
```

**Comment by MarshallOfSound** [comment]
This sounds like a side-effect of `electron-builder` not rebuilding native dependencies in some scenarios.  You should raise an issue with `electron-builder` if they do not supported rebuilding already rebuilt modules.
