### ISSUE TITLE
Can i download headers manual?

### ISSUE THREAD

**Issue by keyiis** [electron/electron-rebuild#121]
Because network is very unstable,i want download headers manual,
1: where should i put  headers file?
2: when run electron-rebuild ,how to set disturl to headers file floder?

**Comment by wenshiqi0** [comment]
Do things like this.
```
electron-rebuild -d=https://gh-contractor-zcbenz.cnpmjs.org/atom-shell/dist/
```

**Comment by MarshallOfSound** [comment]
Thanks @wenshiqi0
