### ISSUE TITLE
 run ./node_modules/.bin/electron-rebuild.cmd failed

### ISSUE THREAD

**Issue by joveth** [electron/electron-rebuild#122]
Well,I'm woking on mac build my electron app,but need pack it for windows ,and used sqlite3.so I need to rebuild node_sqlite3 on windows . All things seem to be ok.But got errors when run the cmd 
`./node_modules/.bin/electron-rebuild.cmd`;

$ ./node_modules/.bin/electron-rebuild.cmd

> electron-prebuilt@1.4.6 postinstall C:\app\node_modules\electron-prebuilt
> node install.js

> sqlite3@3.1.8 install C:\app\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

�ڴ˽���������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�/m�����ء�
MSBUILD : error MSB3428: δ�ܼ��� Visual C++ ������VCBuild.exe����Ҫ���������⣬1) ��װ                                                                                                                                                                                     .NET Framework 2.0 SDK��2) ��װ Microsoft Visual Studio 2005���� 3) ������������                                                                                                                                                                                    ��װ��������λ�ã��뽫��λ�����ӵ�ϵͳ·���С� [C:\app\node_modules\sqlite3\build\binding.                                                                                                                                                                                    sln]
Failed to execute 'C:\Program Files\nodejs\node.exe C:\app\node_modules\npm\node                                                                                                                                                                                    _modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\app\node                                                                                                                                                                                    _modules\sqlite3\lib\binding\electron-v1.4-win32-x64\node_sqlite3.node --module_                                                                                                                                                                                    name=node_sqlite3 --module_path=C:\app\node_modules\sqlite3\lib\binding\electron                                                                                                                                                                                    -v1.4-win32-x64' (1)

node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaw                                                                                                                                                                                    s.com/sqlite3/v3.1.8/electron-v1.4-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@3.1.8 and electron@1.                                                                                                                                                                                    4.6 (electron-v1.4 ABI) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail                                                                                                                                                                                    ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\app\node_modules\npm\node_modules\                                                                                                                                                                                    node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces                                                                                                                                                                                    s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\app\\node_modules\\n                                                                                                                                                                                    pm\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--m                                                                                                                                                                                    odule=C:\\app\\node_modules\\sqlite3\\lib\\binding\\electron-v1.4-win32-x64\\nod                                                                                                                                                                                    e_sqlite3.node" "--module_name=node_sqlite3" "--module_path=C:\\app\\node_module                                                                                                                                                                                    s\\sqlite3\\lib\\binding\\electron-v1.4-win32-x64"
gyp ERR! cwd C:\app\node_modules\sqlite3
gyp ERR! node -v v7.1.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.e                                                                                                                                                                                    xe C:\app\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallbac                                                                                                                                                                                    k-to-build --module=C:\app\node_modules\sqlite3\lib\binding\electron-v1.4-win32-                                                                                                                                                                                    x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=C:\app\node_modul                                                                                                                                                                                    es\sqlite3\lib\binding\electron-v1.4-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\app\node_modules\sql                                                                                                                                                                                    ite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:885:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/chi                                                                                                                                                                                    ld_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\app\\node_m                                                                                                                                                                                    odules\\sqlite3\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fal                                                                                                                                                                                    lback-to-build"
node-pre-gyp ERR! cwd C:\app\node_modules\sqlite3
node-pre-gyp ERR! node -v v7.1.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.31
node-pre-gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\app\\node_modules\\npm\                                                                                                                                                                                    \bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.4.6" "--arch=x64" "                                                                                                                                                                                    --update-binary"
npm ERR! node v7.1.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! sqlite3@3.1.8 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.1.8 install script 'node-pre-gyp install --fall                                                                                                                                                                                    back-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sqlite3
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\app\node_modules\npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (C:\app\node_modules\electron-rebuild\lib\spawn.                                                                                                                                                                                    js:55:26)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

# The Env:
node: v7.1.0
npm: v3.10.9
node-gyp:v3.4.0
node-pre-gyp:v0.6.31
sqlite3:3.1.8
electron:1.4.4
electron-rebuild:1.3.0
windows: Windows_NT 6.1.7601
VS:2015
python:2.7

As I had saw some ERR like ' Microsoft Visual Studio 2005' ,is it need to install vs 2005?
Or some others?
Need helps!!!
Thanks

**Comment by MarshallOfSound** [comment]
`sqlite3` is a `node-pre-gyp` module. As such you need to use the pre-gyp-fix flag (`-p`) when running electron-rebuild
