### ISSUE TITLE
shouldRebuildNativeModules always return true?

### ISSUE THREAD

**Issue by Sunyang730** [electron/electron-rebuild#125]
Hi, I am having this problem where after the rebuild, the shouldRebuildNativeModules always returns true. 

Is this the correct behavior?

**Comment by artemave** [comment]
Seems to be fixed now (v 1.5.5)

**Comment by MarshallOfSound** [comment]
This has been edited handled in 1.5.x

**Comment by Sunyang730** [comment]
Did this got removed or was it fixed? It seems like it always returns true right now. @MarshallOfSound

**Comment by MarshallOfSound** [comment]
@Sunyang730 It got removed, their is now a placeholder which simply returns true in order to maintain the old API working.

We handle the "do we need to rebuild or not" internally now 👍

**Comment by Sunyang730** [comment]
Nice! That's what I figured when I looked at the code @MarshallOfSound
