### ISSUE TITLE
-a not available

### ISSUE THREAD

**Issue by keyiis** [electron/electron-rebuild#126]
When i run this command `>.\node_modules\.bin\electron-rebuild.cmd -a ia32 -f -w sqlite3`,electron-rebuild always generate directory `electron-v1.4-win32-x64`,but i hope `electron-v1.4-win32-ia32`,how to?
OS:win10 x64
NODE:v6.9.2 x64
electron:1.4.12 ia32
electron-rebuild:1.4.0

**Comment by MarshallOfSound** [comment]
The syntax you are looking for is `--arch=ia32`

**Comment by keyiis** [comment]
@MarshallOfSound  please don't close!i already tried!but get same result.

**Comment by MarshallOfSound** [comment]
@keyiis I know this rebuild command with that syntax works as I use it here

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/vendor/rebuild_ia32.bat

And have used it for a long time 👍 I'm happy to help you out if you need it in this issue thread, but it is not a "bug" or "issue" persay so I'll keep it closed for now.

**Comment by keyiis** [comment]
@MarshallOfSound Looks like I'm bad luck, only to solve by manual modify dir name.

**Comment by MarshallOfSound** [comment]
Did you try the `-f` argument?

**Comment by keyiis** [comment]
@MarshallOfSound already tried.  additional remarks:only generate directory not incorrect,but generate  node_sqlite3.node is correct,so the issuse should in generate directory rule.

**Comment by MarshallOfSound** [comment]
@keyiis You probably need to use the node pre gyp workaround documented in the readme. (sqlite3 is pre-gyp)

**Comment by keyiis** [comment]
@MarshallOfSound I added `-p` argument,but still get same result.
