### ISSUE TITLE
1.5.x breaks API as package.json lookup has changed

### ISSUE THREAD

**Issue by halfbyte** [electron/electron-rebuild#132]
Looks like [20c630fe](https://github.com/electron/electron-rebuild/commit/20c630fe623bff3ce58de08ae00f137273b46cd1) introduces a new API (old API being deprecated) but manages to break the old API in the process. 

Found this because electron-rebuild used in ember-electron complained about "...electron-build-tmp/node_modules/package.json" not found. 

Old code has a path.resolve(nodeModulesPath, '..','package.json') whereas new code seems to expect the parent directory.

As 1.5.x should be API compatible (if taking SemVer into account) to 1.4.0, I'd consider this a bug.

**Comment by paulcbetts** [comment]
I think this is fixed in the latest version - any breaking API changes in 1.5.x is considered a bug for sure

**Comment by paulcbetts** [comment]
-cc @MarshallOfSound

**Comment by ide** [comment]
The dependency resolver seems to skip transitive dependencies more than two levels deep. So if your dep graph looks like APP --> DEP1 --> DEP2 --> DEP3, electron-rebuild finds DEP1 and DEP2 but not DEP3 (and DEP4, etc).

**Comment by MarshallOfSound** [comment]
@ide Can you provide a sample package.json for that situation.  We have tests for nested transitive dependencies and as far as I can see they are getting rebuilt.

**Comment by MarshallOfSound** [comment]
@halfbyte  The latest version should resolve the rebuild target folder correctly

**Comment by ide** [comment]
@MarshallOfSound This is the package.json in question - https://github.com/exponent/xde/blob/master/app/package.json

There are only prod deps so I'd expect all packages under node_modules to be listed as "scanning..." when rebuilding with DEBUG=electron-rebuild, but they aren't all there.

**Comment by MarshallOfSound** [comment]
@ide Just cloning to take a look now

**Comment by ide** [comment]
@MarshallOfSound Thanks, I just pushed a branch that made some Gulpfile changes so it calls the 1.5.x API: https://github.com/exponent/xde/tree/electron-rebuild, tested with `DEBUG=electron-rebuild gulp rebuild` after installing node_modules in the project root and the `app` subdirectory.

**Comment by halfbyte** [comment]
@MarshallOfSound It wasn't working this morning with a clean install. Now I've tested it with 1.5.4 pinned in the package.json and get the same error.

[Here are the relevant lines in the calling code](https://github.com/felixrieseberg/ember-electron/blob/master/lib/commands/package.js#L331-L348) that works with 1.4.0 and breaks with 1.5.4. 

I can try to set up a full test project (as mine is private and commercial yadda, yadda) if that would help. I'll try to look at the last few commits to figure out what is going on, too.

**Comment by MarshallOfSound** [comment]
@ide I think I have found the issue (woops).  Can you confirm that your transitive dependencies you expect to be rebuilt are `ffi` and `ref`?

**Comment by MarshallOfSound** [comment]
@halfbyte Hmm, fix incoming.

**Comment by MarshallOfSound** [comment]
@ide Thanks for pointing in the right direction for that issue, turns out we were ignoring super hoisted dependencies (dependencies hoisted to the top level from deep in the tree), should be all sorted for you now 👍

**Comment by halfbyte** [comment]
@MarshallOfSound @paulcbetts Can confirm fix working, awesome, thanks a lot for the quick fix.

❤️  🏆  👍

**Comment by ide** [comment]
@MarshallOfSound I didn't investigate deeply enough to determine if `ffi` and `ref` were the packages in question that I needed to rebuild, I just noticed that rebuilding was finishing extremely quickly and that the list of scanned modules was smaller than the total set of transitive dependencies, you've investigated deeper than I have at this point :) Thanks for the super quick fix too, I will try it out!
