### ISSUE TITLE
Cannot locate node-gyp due to system directory structure

### ISSUE THREAD

**Issue by glek** [electron/electron-rebuild#143]
As of commit 8f51c7ea179eef48232d9e93b77b9f9a370b3710, my copy of electron-forge is unable to start my application. It fails on trying to rebuild native dependencies saying it cannot located node-gyp.

I dug around and traced the error back to the `rebuild.js` file in this project.

I believe that because of how node-gyp is located after the above mentioned commit, it's triggering my problem. On Arch Linux (and perhaps other Linux systems) with Node v5.7.0 and NPM 4.1.2, packages installed via `npm install -g` have their executable files sym-linked to `/usr/bin/` instead of `/usr/lib/node_modules/.bin`, which is what electron-rebuild is looking for.

More details are available on request.

**Comment by MarshallOfSound** [comment]
@glek Sorry for the delay in getting to this, I missed this one in my notifications 👍 

First off is this still an issue? 😆 

If so can you comment the result of `npm ls node-gyp` in your project's folder.  `node-gyp` should be being resolved relative to the install of `electron-rebuild` as it is a dependency of `electron-rebuild`.

**NOTE:** If you installed `-rebuild` globally then you need to run `npm ls node-gyp --global`

**Comment by glek** [comment]
The issue has strangely vanished at this time. If it reappears, I will re-open the issue, but for now all seems to be working normally.
