### ISSUE TITLE
Support electron ^1.6.0

### ISSUE THREAD

**Issue by MikeLP** [electron/electron-rebuild#145]
It's throwing an error for electron version 1.6.0. 
Why it's important to support for me? Because this version support native async|await and few other critical features. Thanks.

`✖ Rebuild Failed
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 1.6.0 and runtime electron

Error: Could not detect abi for version 1.6.0 and runtime electron`

**Comment by MarshallOfSound** [comment]
`node-abi` has been updated to support Electron 1.6.0

If you run `npm update` you should get the new version of `node-abi`.

If that doesn't work then simply

```bash
npm uninstall electron-rebuild
npm install electron-rebuild
```

And that will re-resolve the dependency tree, sorry for the hassle 👍

**Comment by MarshallOfSound** [comment]
FYI submitted lgeiger/node-abi/pull/13 to make the error message it outputs slightly more informative
