### ISSUE TITLE
Could not detect the Python executable based on `npm config ls`

### ISSUE THREAD

**Issue by fyears** [electron/electron-rebuild#146]
I am on Windows, and I have Python 3 in the command line for general Python programming.

```bash
$ python --version
Python 3.5.1 :: Continuum Analytics, Inc.
```

To enable `node-gyp`, I use [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools) to install Python **2** and configure `npm` as desired:

```bash
$ npm config ls
scope = ""
user-agent = "npm/4.3.0 node/v6.3.1 win32 x64"

msvs_version = "2015"
python = "C:\\Users\\username\\.windows-build-tools\\python27\\python.exe"

prefix = "C:\\Users\\username\\AppData\\Roaming\\npm"
```

I still get the following error while running `electron-rebuild` because `electron-rebuild` could not find the correct Python 2 based on `npm config ls`:

```bash
$ npm install zerorpc # the package I could not bind to electron
$ npm install electron electron-rebuild

$ ./node_modules/.bin/electron-rebuild
× Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.5.0
gyp info using node@6.3.1 | win32 | x64
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "C:\Anaconda3\python.EXE", you can set the PYTHON env variable.
...
```

Expected result: no errors, and the package could detect the Python 2 executable properly.

**Comment by Bizarrus** [comment]
Same problem here!

**Comment by abhideshmukh** [comment]
It is not compatible with python 3.x.x . Try to install ^2.7.x (the lest one).

**Comment by paulinodjm** [comment]
Same problem with python 3.5.2.
Rebuild completed after installing python 2.7.14 and updating the `PYTHON` environment variable.

**Comment by MarshallOfSound** [comment]
Don't know why this stayed open so long :laughing:

But yeah, python 3.x doesn't work with node-gyp, you need python 2.x as people in this thread have already determined

**Comment by autotel** [comment]
For people who have the latest version of python, the error message doesn't help much. It should tell that there is no python, or its version is not compatible.
