### ISSUE TITLE
Rebuild native extension

### ISSUE THREAD

**Issue by pronebird** [electron/electron-rebuild#150]
I have a native extension and I'd like to test it using electron-mocha. How can I run tests and make sure that the installed version of electron and extension that I built with  #node-gyp are both built using the same runtime and are compatible?

I tried running `./node_modules/.bin/electron-rebuild .`, it says `✔ Rebuild Complete` but I am sure it didn't do anything. 

It seems that electron-rebuild only targets modules by name but that's not the case here since my package.json is the module itself. Is it possible to point electron-rebuild to module.node or source code or bindings.gyp so it could do its magic?

Running electron throws error:
> Module version mismatch. Expected 50, got 48.

**Comment by MarshallOfSound** [comment]
Hm, so the top level module is actually your native module.  Didn't see that one coming 😆 

Should be relatively straightforward to check the top level module in our exploration stage.

**Comment by brandonwamboldt** [comment]
This would also be useful to me.

**Comment by teshoudong** [comment]
I have the same questio

**Comment by wenshiqi0** [comment]
This can be helpful.

**Comment by MarshallOfSound** [comment]
I completely failed when committing this but this is now handled on this line in this commit 😆 

https://github.com/electron/electron-rebuild/commit/885e9edc18d1d160be2e2a4ea419ed0451b0534c#diff-e954a0c620ecfedccb6c501ac9f5d046R83

Basically, we now check the root module as well so in your native module just run `electron-rebuild .` and it should work (note not released yet)

**Comment by pronebird** [comment]
Thank you @MarshallOfSound! This is pretty awesome! Was this ever released?

**Comment by MarshallOfSound** [comment]
@pronebird Doesn't look like it, I'll try cut a new release of `-rebuild` soon

**Comment by pronebird** [comment]
@MarshallOfSound no rush. Thanks for heads up :)
