### ISSUE TITLE
-w gets ignored

### ISSUE THREAD

**Issue by LukasBombach** [electron/electron-rebuild#151]
I am trying to rebuild the package `vlc` like so

```
./node_modules/.bin/electron-rebuild -v 1.4.15 -f -w vlc
```

but instead of rebuilding `vlc` another package, `sqlite3`, gets rebuild

> Building module: sqlite3, Completed: [num]

and then it finishes. when I provide no package with `-w` I see the same output (same package being rebuilt)

**Comment by MarshallOfSound** [comment]
Tbh this is a logging issue more than a bug I think.  Check what is actually being rebuilt by running electron-rebuild with DEBUG=electron-rebuild*

**Comment by wildermuthn** [comment]
I can confirm that this doesn't work, and that rebuild.js gets passed in the -w argument as "extraModules" — adding them to the list of modules found by scanning the node_modules directory.

**Comment by MarshallOfSound** [comment]
@wildermuthn So to confirm the issue is that you expect `-w` to build **only** those modules and that isn't the case?

**Comment by McPo** [comment]
@MarshallOfSound  Yes. Experiencing the same issue myself.

**Comment by rllola** [comment]
@MarshallOfSound I was also expecting it to **only** rebuild the modules given after `-w` but it does rebuild also the rest of my native modules.
