### ISSUE TITLE
Use electron dependency instead electron-prebuilt

### ISSUE THREAD

**Issue by darky** [electron/electron-rebuild#154]
Because https://github.com/electron-userland/electron-prebuilt/issues/234#issuecomment-285879644

**Comment by malept** [comment]
I think `package.json` still needs to reference electron-prebuilt because it still needs to work with that module. (Electron tools need to work with as many prebuilt Electron node modules as possible.) However, the readme should probably be updated. (That's happening in #142.)

**Comment by darky** [comment]
Can I somehow to build native modules for electron 1.6.x?

**Comment by malept** [comment]
Worked for me:
```
npm install -g electron-forge
electron-forge init native-example
cd native-example
npm install --save ref
npm run package
```

`ref` is a native module.

**Comment by darky** [comment]
@malept, thanks! This works, but process very excess and redudant.
In addition it places *node_modules* to *out/native-linux-x64/resources/app*, that make hard my existing deploy process...
Would be better to have working this guide, where simply rebuilds existing node_modules https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md, but it try download and compile **iojs** target instead **electron**
But thanks anyway, it better, than nothing!

**Comment by malept** [comment]
Using Electron Forge is just a convenient way for me to prove that rebuilding modules with the latest version of Electron works without any configuration. Since you have an existing project, you are more than welcome to use electron-rebuild on its own.
