### ISSUE TITLE
Building module: 'serialport', Completed: 0

### ISSUE THREAD

**Issue by zhoufeifan** [electron/electron-rebuild#157]
when I run 'electron-rebuild' command,it always show  "Building module: 'serialport', Completed: 0",and the progress always be 0, I don`t know how to  solve it, please help me !

**Comment by MarshallOfSound** [comment]
Run the command with DEBUG enabled and let it run for a while.  On a slow machine it could take a fair amount of time

**Comment by MarshallOfSound** [comment]
No response in a very long time so closing out, if the DEBUG information is provided this can be revisited
