### ISSUE TITLE
ref node version error

### ISSUE THREAD

**Issue by cdburke** [electron/electron-rebuild#158]
I get a node version error when using ref from electron, and using electron-rebuild makes no difference. In the example below, is electron-rebuild being called correctly?

The error message:

Uncaught Error: The module '/home/chris/electron-quick-start/node_modules/ref/build/Release/binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).

---------------

~$ node --version
v7.7.4
~$ npm --version
4.1.2

---------------

To reproduce:

cd ~
rm -rf electron-quick-start
git clone https://github.com/electron/electron-quick-start.git
cd electron-quick-start
npm install --save-dev electron-rebuild
npm install
./node_modules/.bin/electron-rebuild
npm install ref
./node_modules/.bin/electron-rebuild
#replace comment line with require('ref'):
sed -i "/also require/c\    require('ref')" index.html
npm start

**Comment by MarshallOfSound** [comment]
Electron rebuild only rebuilds production dependencies so you need to install ref with "--save" or ensure it is in the dependencies section of your package.json

**Comment by mohit-sharma14** [comment]
I have also experiencing the same issue.
