### ISSUE TITLE
electron rebuild cannot find node-pre-gyp-fix

### ISSUE THREAD

**Issue by JoshuaKrstic** [electron/electron-rebuild#160]
Electron 1.3.3, Electron-rebuild 1.5.7
Mac OSx Sierra

I ran `$ node_modules/.bin/electron-inspector`
expecting to start electron inspector following this guide: https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process-node-inspector.md

and got the following output:

node-inspector binaries are incompatible or missing.
Attempting to rebuild...
Failed to load electron-prebuilt, abandoning rebuild.
(node:6769) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module 'electron-rebuild/lib/node-pre-gyp-fix'

(Sorry for lack of code box, the whole error message doesn't appear when I put it in one...)

**Comment by malept** [comment]
Thanks for filing a bug, but electron-inspector hasn't been upgraded to use electron-rebuild 1.5.x, this is an upstream issue:

https://github.com/enlight/electron-inspector/issues/7

**Comment by JoshuaKrstic** [comment]
Awesome...

Thanks for the info
