### ISSUE TITLE
-w randomNameThatDoesntExists always returns "rebuild complete"

### ISSUE THREAD

**Issue by scedge** [electron/electron-rebuild#161]
You can pass any arbitrary name with -w and it will return as successful.

Is this working as intended?

**Comment by MarshallOfSound** [comment]
@scedge Yes, this is intended behavior.  Personally I don't see why this should be an error.

**Comment by fab1an** [comment]
Well the option `-w` means "build this module". If  `electron-rebuilt` replies "Rebuild complete.", that suggests it built this module, which it didn't...
