### ISSUE TITLE
Support modules with bundled prebuilds for electron

### ISSUE THREAD

**Issue by mafintosh** [electron/electron-rebuild#162]
All new native modules I've been writing, use a new technique where I bundle all prebuilds inside the npm tarball and the pick the right one at runtime. A huge benefit of this is that using these modules with electron *just works*, no compilation needed.

However when people use electron-rebuild, it forces the prebuilded modules to rebuild by running `node-gyp rebuild` instead of running the install script if present in package.json. Ironically this breaks some of my modules that support electron out of the box cause it tries to recompile them without running a preinstall script specificed by the install script.

Anyway to fix this?

As an example try my [sodium-native](https://github.com/mafintosh/sodium-native) module. It is a native module that works across node/electron without needing any recompilation that breaks when electron-rebuild tries to recompile it, cause it isn't running the install script instead node-gyp like npm does.

**Comment by mafintosh** [comment]
Idea: A fix would be to run the install script with electron if present. Thoughts?

**Comment by blahah** [comment]
can confirm, I have to do:

```
cd node_modules/sodium-native && npm run preinstall && cd - && electron-rebuild
```

to stop electron-rebuild erroring out with sodium-native.

**Comment by mafintosh** [comment]
Alternatively a quick fix would be a `--skip` option that I can tell people to use when using my modules that support electron.

**Comment by mafintosh** [comment]
FYI, this works perfectly fine, `npm rebuild --runtime=electron --target=$(electron --version) --disturl=https://atom.io/download/atom-shell --abi=$(electron --abi)`

**Comment by blahah** [comment]
@mafintosh is the `--dist-url` argument necessary?

**Comment by blahah** [comment]
oh I see, because this is just npm rebuild it won't have the headers otherwise 👍

**Comment by MarshallOfSound** [comment]
@mafintosh I was talking with someone working on Rust a while back and we were discussing a similar issue to this one.  The potential solution we arrived on was checking if the module exposed a "electron-rebuild" script, and if so we would run that instead of the node-gyp rebuild.

Would this be a valid solution for your issue as well?

**Comment by mafintosh** [comment]
@MarshallOfSound My main use case is just skipping any recompile steps as my thing already works on electron so yes. However if you electron-rebuild just ran the script I linked I wouldnt have to make any changes so much prefer that.

**Comment by MarshallOfSound** [comment]
@mafintosh That command rebuilds everything in the current npm module including nested and transitive dependencies regardless of type, rebuild state and other factors we care about.  The reason we use the current strategy is to avoid rebuilds when the module has already been built and to avoid rebuilding development dependencies / other dependencies a user wishes to ignore.

**Comment by mafintosh** [comment]
@MarshallOfSound couldnt you just only execute that command in the deps you wanna rebuild? Or do the equivalent of what the command does yourself in the repos you wanna rebuild?

**Comment by MarshallOfSound** [comment]
@mafintosh Executing `npm rebuild` doesn't just affect the module in the CWD it affects all that modules dependencies as well which can have wild side effects.  Also it means we can't track if the module is rebuilt for Electron or not.  I'd much prefer to find a solution which doesn't involve a fundamental change in how we rebuild modules.

Is there some kind of script, file or dependency that we can search for to exclude your electron compatible prebuilts from our list?

Without know how your prebuilt scripts work could you simply create a `.forge-meta` file in the correct place so we don't attempt to rebuild the module?

https://github.com/electron/electron-rebuild/blob/master/src/rebuild.ts#L99

**Comment by mafintosh** [comment]
@MarshallOfSound yea you can look for `./prebuilds/{platform}-{arch}/electron-{electron-abi}.node`. fx on macOS (darwin) it'll look like this, `prebuilds/darwin-x64/electron-50.node`. If that file is present you should just skip the recompilation. That'd be super awesome!!

**Comment by blahah** [comment]
@MarshallOfSound please could you cut a new release with this fix?
