### ISSUE TITLE
Compile Error： invalid file or disk full

### ISSUE THREAD

**Issue by kazusa0106** [electron/electron-rebuild#163]
rebuild the module named ‘serialport’ and got this：
**C:\Users\user\.electron-gyp\.node-gyp\iojs-1.4.13\Release\iojs.lib : fatal error LNK1106: invalid file or disk full: cannot seek to 0xF2ADE [E:\vueFrame\test\printtest\node_modules\serialport\build\serialport.vcxproj]**

but node-gyp rebuild is OK under the directory  ".../node_modules/serialport"

Of cousre I've checked my disk.

node version: 6.9.1
electron version:1.6.2
OS:win7 x64

**Comment by MarshallOfSound** [comment]
> Of cousre I've checked my disk.

Haha, good start 😆 

> cannot seek to 0xF2ADE 

Can you try wiping your ".electron-gyp" folder and trying again, if that doesn't help I can only suggest running disk check 😢 Your actual HDD might be the issue here

**Comment by nrakochy** [comment]
Ran into the same issue when upgrading node/node-gyp/windows-build-tools. Deleting the .electron-gyp directory worked for me. Thanks.

**Comment by MarshallOfSound** [comment]
Due to lack of response from the original reporter and confirmation from a third party the suggested work around worked I'm going to close this out 👍
