### ISSUE TITLE
electron-rebuild didn't work for node-hid without being global

### ISSUE THREAD

**Issue by huogerac** [electron/electron-rebuild#167]
Hi,
Not sure if it's a problem or not. If you confirm, I could send a PR updating the README file.

Context:
I was getting "Module version mismatch. Expected 50..." error for the node-hid module.
Then, I used the electron-rebuild as the documentation says and didn't work.
I've tried many ways, using -m and -w and nothing worked as expected..

Finally, one friend told me to install electron-rebuild globally instead!
And it worked!
Weird, right? But just commenting here just in case some one has the same Issue.

**Comment by MarshallOfSound** [comment]
Installing globally shouldn't affect the way `electron-rebuild` works, if it did you probably ended up with a different version globally than you did locally which probably fixed whatever issue you were experiencing.  Closing out as a non-issue
