### ISSUE TITLE
Can not find module 'babel-runtime/regenerator'

### ISSUE THREAD

**Issue by wangpin34** [electron/electron-rebuild#169]
Previously I rebuilt packages by electron-rebuild@1.5.7.  Today I  updated it to v1.5.9 but it is failed at the very beginning of rebuild process. I digged the code into node_modules/electron-rebuild/lib/cli.js and found following 
```javascript
var _regenerator = require('babel-runtime/regenerator')
```
It seems like babel-runtime/regenerator is required but the very strange thing is it had been removed from dependencies of package.json recently.  

By the way, I downgraded it to v1.5.7 and it worked fine.  

Hope you guies could have a look about this.

node v6.10.2
npm v4.3.0
electron-rebuild v1.5.9

**Comment by MarshallOfSound** [comment]
Fixed in `1.5.10`, leftover bug from the typescript conversion 👍
