### ISSUE TITLE
"electron-rebuild --version" should give a better error message

### ISSUE THREAD

**Issue by simark** [electron/electron-rebuild#173]
Using `-v` or `--version` fails:
```
$ ./node_modules/.bin/electron-rebuild --version
An unhandled error occurred inside electron-rebuild
Unable to find parent node_modules directory, specify it via --module-dir, E.g. "--module-dir ." for the current directory

Error: Unable to find parent node_modules directory, specify it via --module-dir, E.g. "--module-dir ." for the current directory
    at Object.<anonymous> (/tmp/test/node_modules/electron-rebuild/lib/src/cli.js:79:23)
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/test/node_modules/electron-rebuild/lib/src/cli.js:5:58)

```

**Comment by simark** [comment]
I assumed that `--version` was to show the version of electron-rebuild, I just notice that it's not the case:

    -v, --version                The version of Electron to build against

In that case, the (user) error could be handled more gracefully.

**Comment by MarshallOfSound** [comment]
We could explicitly check for this case and either

* Output the version of `electron-rebuild` as it's what the user wants
* Return a nicer error with usage
