### ISSUE TITLE
Default types are "prod,dev" for CLI, not "prod,optional"

### ISSUE THREAD

**Issue by romaincointepas** [electron/electron-rebuild#179]
See https://github.com/electron/electron-rebuild/blob/master/src/cli.ts#L101

`argv.t ? argv.t.split(',') : ['prod', 'dev']`

The doc/help says: `Default is "prod,optional"`

**Comment by MarshallOfSound** [comment]
Woops, simple to fix 👍 Would take a small PR 😄

**Comment by romaincointepas** [comment]
@MarshallOfSound done! #180
