### ISSUE TITLE
It still doesn't work when I used "electron-rebuild -f -w realm"

### ISSUE THREAD

**Issue by DoubleWoodH** [electron/electron-rebuild#182]
ERROR in ./~/realm/lib/browser/index.js
    
    Module not found: Error: Can't resolve 'react-native' in
    '/Users/H/Documents/MyApp/node_modules/realm/lib/browser'
     
    @ ./~/realm/lib/browser/index.js 21:0-45
    
    @ ./~/realm/lib/index.js
     
    @ ./render/routes/tools/Network.js
     
    @ ./render/router.js
     
    @ ./render/index.js
     
    @ multi (webpack)-dev-server/client?http://localhost:9527 webpack/hot/dev-server react-hot-loader/patch webpack-dev-server/client?http://localhost:9527/ webpack/hot/only-dev-server ./render/index.js
    
    Not rewriting GET /dist/bundle.js because the path includes a dot (.) character.

I want to use `realm` in an `electron` app, and I just used the code below but it still doesn't work, and the error imformation is above, even though I used `electron-rebuild -f -w realm`

    const Realm = require('realm')

**Comment by MarshallOfSound** [comment]
This isn't anything to do with native modules or `electron-rebuild`.  For some reason that module is trying to require `react-native` which doesn't seem right for a module you want to use in Electron.  I'd reccomend asking upstream in Realm how you are supposed to use it.

**Comment by DoubleWoodH** [comment]
Thanks so much.
