### ISSUE TITLE
electron-rebuild -f -w=app/node_modules/node-pty -w invalid

### ISSUE THREAD

**Issue by hengkx** [electron/electron-rebuild#191]
electron-rebuild -f -w=app/node_modules/node-pty -w invalid

node -v 8.1.3
npm -v 5.0.3
electron-rebuild -v 1.5.11

**Comment by MarshallOfSound** [comment]
Insufficient information, what is the issue here?

**Comment by hengkx** [comment]
@MarshallOfSound Executing `electron-rebuild -f -w=app/node_modules/node-pty` statement also compiles the `fsevents`

**Comment by MarshallOfSound** [comment]
This is expected behavior.  If you want to build a single module you will have to wait for this PR.

https://github.com/electron/electron-rebuild/pull/190
