### ISSUE TITLE
Hard to rebuild with lerna

### ISSUE THREAD

**Issue by akosyakov** [electron/electron-rebuild#192]
We use [lerna](https://lernajs.io/) with hoisting. It means that dependencies to rebuild are declared in a local child module but the real dependency is installed in the root module. With such configuration, it is impossible to use electron-rebuild without redeclaration of child dependencies in the root package.

**Comment by MarshallOfSound** [comment]
@akosyakov You can use `-w` to add modules to the rebuild list that aren't in your `package.json`

**Comment by akosyakov** [comment]
@MarshallOfSound Please reopen. I've tried, it does not make any difference without redeclaring dependencies in package.json. It seems that `-w` ignored if dependencies in package.json are empty.

**Comment by MarshallOfSound** [comment]
@akosyakov Try the new `--only` then, although `-w` should work 🤔

**Comment by akosyakov** [comment]
You can reproduce it with [Theia](https://github.com/theia-ide/theia):
- check it out
- run `yarn` to set everything up
- then remove `node-pty` from dependencies of the root package and run `DEBUG=electron-rebuild` + `./node_modules/.bin/electron-rebuild -w=node-pty` from the root
- see `node-pty` is not rebuilt

**Comment by akosyakov** [comment]
Another thing we use the same node_modules to run in the electron and browser environments and have [a script to roll back results of rebuild](https://github.com/theia-ide/theia/blob/master/scripts/rebuild.js). It works but we only assume what is rebuilt. It would be nice if `electron-rebuild` can backup rebuilt modules and able to roll back changes since it knows better.

**Comment by hexa00** [comment]
Friendly ping to re-open ?

Thanks,

**Comment by Ciantic** [comment]
This issue exists also with Yarn workspaces, since packages gets hoisted.

E.g. 
```
./node_modules/ref/
```
can't be rebuilt with electron-rebuild because it's dependencies e.g. debug and nan are in the
```
./node_modules/debug/
./node_modules/nan/
```
The electron expects them to be 
```
./node_modules/ref/node_modules/
```
And throws an error, since that does not exist.

I fixed this by hoisting the rebuild dependencies to the package.json in the root of your workspace, it's not pretty, but then the rebuild works.
