### ISSUE TITLE
Does not rebuild when dependency is in `devDependencies`

### ISSUE THREAD

**Issue by fab1an** [electron/electron-rebuild#194]
I have my dependencies in `devDependencies` (for reasons).

`electron-rebuild` always exits with "rebuild complete" without actually building anything.

**Comment by MarshallOfSound** [comment]
Check out the documentation in the README, in particular the `--types` parameter

```
  -t, --types                  The types of dependencies to rebuild.  Comma
                               seperated list of "prod", "dev" and "optional".
                               Default is "prod,optional"
```

**Comment by fab1an** [comment]
Thanks.

**Comment by MarshallOfSound** [comment]
@fab1an You can also use the `-w` parameter to add individual modules to the list of things to rebuild

**Comment by fab1an** [comment]
@MarshallOfSound I did that, but they are ignored if "--types" is not specified.
