### ISSUE TITLE
"command not found" in OSX

### ISSUE THREAD

**Issue by Janneman84** [electron/electron-rebuild#197]
I'm trying to run electron-rebuild in OSX but apparently I'm doing something wrong. I'm just following the instructions in the readme and I can't seem to find any other examples anywhere else.

The electron-rebuild folder is in the node_modules. How do I actually run it? I just keep getting "command not found" if I enter "electron-rebuild" in terminal.

**Comment by MarshallOfSound** [comment]
I would recommend reading the README as it has a section on different ways to run `electron-rebuild`.

https://github.com/electron/electron-rebuild#how-does-it-work

```bash
$(npm bin)/electron-rebuild
```

**Comment by Janneman84** [comment]
Yeah I read and tried that of course. First of all I'm not sure what you mean by "(npm bin)". I suppose you mean the 'electron-rebuild' folder in 'node_modules'. I navigated there and tried 'electron-rebuild' but it didn't work.

I tried installing it globally with -g instead and now it works :).

**Comment by MarshallOfSound** [comment]
@Janneman84 You literally just run that command

```bash
$(npm bin)/electron-rebuild
```

`npm bin` outputs the path to the local `.bin` folder

**Comment by Janneman84** [comment]
Haha this works,  that was just too easy :)

Apparently I'm thinking too much, I just thought it was some kind of placeholder... Also I thought the dollar sign represented the dollar sign of the prompt (however inconsistent with the other examples).

Anyway, thanks!
