### ISSUE TITLE
Using io.js?

### ISSUE THREAD

**Issue by Stanzilla** [electron/electron-rebuild#198]
So every time I run electron-rebuild on a project (https://github.com/zeit/hyper) that uses node-pty it downloads and uses iojs-1.6.12 and I have a hard time figuring out why and where this comes from.

Using Windows 8.1 x64 here.

**Comment by malept** [comment]
Looks like that's what the Node header tarball is named: https://github.com/electron/electron/blob/717a1a666cabf0479bdc981ef7f08663804d050a/script/create-node-headers.py#L42-L43

**Comment by Stanzilla** [comment]
Ugh okay, I was so confused, especially since iojs-1.6.12 is not even a thing. Thank you!
