### ISSUE TITLE
Returning Nan::Buffer from native addon very slow

### ISSUE THREAD

**Issue by justadudewhohacks** [electron/electron-rebuild#212]
In a native addon I am creating a node buffer via Nan::NewBuffer. Now if I am rebuilding the addon with electron-rebuild `info.GetReturnValue().Set(buf)` seems to be very slow. 

For example I am returning a buffer with image data of an 800x320 sized image. In a simple node.js script measured with console.time, returning the node buffer takes less then a millisecond. Doing the exact same thing with electron however takes more than 100ms. The native module is rebuild with electron-rebuild and required via electron.remote: `var cv = require('electron').remote.require('opencv4nodejs')`.

I am not familar with the internals of electron and how electron-rebuild works so it would be nice if someone could shed some light on this issue.

Environment:
- win7 64bit
- node v9.2.0
- electron@1.7.8
- electron-rebuild@1.6.0

**Comment by jrobeson** [comment]
This isn't a bug in electron-rebuild is it? I think you need to file the issue somewhere else.

**Comment by justadudewhohacks** [comment]
This isn't a bug actually, turned out I was requiring the module via electron.remote, which caused buffers to be serialized.
