### ISSUE TITLE
rebuild fails when using packages direct from git missing package.json

### ISSUE THREAD

**Issue by xoorath** [electron/electron-rebuild#215]
Hey,

I'm working on a kind of unique use case in my C++ application that leans on a lot of node tech. In my use case I have some of my third party dependencies linked directly to git repositories that don't include a `package.json` .

```
"dependencies": {
    "bgfx": "https://github.com/bkaradzic/bgfx.git#f88c44a835a753818bbd90832934df6e2654ead1",
    "bimg": "https://github.com/bkaradzic/bimg.git#886ba55a25db213719c96116f9eabb188b946571",
    "bindings": "^1.3.0",
    "bx": "https://github.com/bkaradzic/bx.git#148bdc60fa25cf29ae0704caa842af4bd8a77820",
    "colors": "^1.1.2",
    "decompress": "^4.2.0",
    "electron-rebuild": "^1.6.0",
    "extract-zip": "^1.6.6",
    "mv": "^2.1.1",
    "nan": "^2.8.0",
    "three": "^0.88.0"
  },
"devDependencies": {
    "electron": "1.7.9"
  }
```

When I run electron-rebuild, it takes issue with bgfx, bimg, and bx since they don't have a package.json. I'd be happy enough to see a warning in this case, or have an option to suppress this error (or warning) for all or some set of packages.

Is this possible currently? If not my available workaround seem.... less than ideal. Really seems like something I'd have a hard time solving in my workflow without an update to electron-rebuild.

The error I'm getting, by the way:
```
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
ENOENT: no such file or directory, open 'D:\Projects\Github\urban-spork\node_modules\bgfx\package.json'

Error: ENOENT: no such file or directory, open 'D:\Projects\Github\urban-spork\node_modules\bgfx\package.json'
```

**Comment by xoorath** [comment]
I'm in no rush since I added this ugly hack that seems to work fine:
```
echo {} > ./node_modules/bgfx/package.json
echo {} > ./node_modules/bx/package.json
echo {} > ./node_modules/bimg/package.json

call .\node_modules\.bin\electron-rebuild
```

If you folks don't have time, but know how it would be fixed, I'd be happy to make a PR with someone pointing me in the right direction for an appropriate fix.

**Comment by kimorkim** [comment]
I have a similar problem.
There is a project using `bower` and the `bower` recommends changing to `yarn`.
If this use `yarn`, it will be part of node_module.
Many `bower` projects do not have package.json.
So, the following error occurs.

``` bash
✖ Preparing native dependencies

An unhandled error has occurred inside Forge:
ENOENT: no such file or directory, open '/Users/Naver/entry-offline/node_modules/@bower_components/EaselJS/package.json'
Error: ENOENT: no such file or directory, open '/Users/Naver/entry-offline/node_modules/@bower_components/EaselJS/package.json'
```
What should I do to solve this problem?

**Comment by MarshallOfSound** [comment]
Providing a `package.json` in the correct solution to this issue, it's not technically a valid node module without one.  In an upcoming version we might handle this a bit nicer (not throw but just ignore the missing package.json) but for now this is a user space issue 👍

**Comment by xoorath** [comment]
@MarshallOfSound It looks like `read-package-json` is already setup to handle this nicely.  I'd recommend testing with `safe = true` as a param before closing the issue.

If it is a user space, I'd have to consider it a bug that npm lets you download from any git repo that doesn't have a package.json; but so long as we can agree that isn't a bug but a feature, then I'd say it's worth handling correctly here (especially if it is a low hanging fruit)... It's not like I'm cramming random folders into `node_modules`, I'm using nmp and my own package module to get this dependency. 😄 

Not sure if you'll agree with that, which is fair - but that's my take.
