### ISSUE TITLE
Google RPC add-on is building into an incorrectly named folder

### ISSUE THREAD

**Issue by mattcollier** [electron/electron-rebuild#217]
This has to do with [electron-speech-recognition](https://github.com/mattcollier/electron-speech-recognition).  The build ultimately works properly, but the build binary for [@google-cloud/speech ](https://github.com/googleapis/nodejs-speech) folder must be renamed as shown here:
https://github.com/mattcollier/electron-speech-recognition/blob/master/rename-grpc-binary.sh

I don't know if that's a problem with the grpc node-gyp configuration, an issue with electron-rebuild or what.  Can anyone point me in the right direction?

#### Environment details

  - OS: Debian 9
  - Node.js version: Electron 1.6 and 1.7
  - npm version: 5.5.1
  - @google-cloud/speech version: 1.0.0

See also: https://github.com/googleapis/nodejs-speech/issues/11

**Comment by MarshallOfSound** [comment]
This issue here is the usage of the `node-pre-gyp` variable `{libc}`, we don't handle that and to be honest I have no idea what it is or how to compute it.

We do our other variable replacement here: https://github.com/electron/electron-rebuild/blob/master/src/rebuild.ts#L195

If you know how to correctly generate the value to put in that variable we can patch it up 👍

**Comment by mattcollier** [comment]
@MarshallOfSound thanks for the tip!  I was able to find this issue which describes the recently added {libc} versioning token.  I will look at the `node-pre-gyp` implementation and put together a PR if I can.

https://github.com/mapbox/node-pre-gyp/issues/325

**Comment by mattcollier** [comment]
@MarshallOfSound turns out `node-gyp@0.6.39`, which contains the`{libc}` token support, is getting installed despite the fact that 0.6.39 is not displayed under github releases.  I guess the release did not get tagged properly.

Here is the PR : https://github.com/mapbox/node-pre-gyp/pull/326/files

Is this just a matter of adding a `detect-libc` dependency and using it to resolve the token when present?  Is the `--target_libc` option referenced in the PR anything to be concerned about here?
