### ISSUE TITLE
Unable to install with node-libcurl

### ISSUE THREAD

**Issue by Acidic9** [electron/electron-rebuild#227]
I'm attempting to install [node-libcurl](https://github.com/JCMais/node-libcurl) into my electron application. This issue may not be mainly because of electron-rebuild, I am just mainly looking for some help.

I am running Windows 10 64bit.

To replicate my issue, in gitbash terminal, I enter the following commands...

```bash
npm init -y                             # Successfully initializes

npm install node-libcurl                # Successfully builds with `node-pre-gyp install --fallback-to-build`

npm install --save-dev electron-rebuild # Fails
```

The output of the last command (install electron-rebuild) is the following...

```bash
$ npm install --save-dev electron-rebuild

npm WARN tst@1.0.0 No description
npm WARN tst@1.0.0 No repository field.

npm ERR! path C:\Users\Arise\tst\node_modules\node-libcurl\node_modules\abbrev
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Arise\tst\node_modules\node-libcurl\node_modules\abbrev' -> 'C:\Users\Arise\tst\node_modules\node-libcurl\node_modules\.abbrev.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arise\AppData\Roaming\npm-cache\_logs\2018-02-20T13_06_13_960Z-debug.log
```

---

After tackling this issue for quite some time, I made a golang program within `node_modules/node-libcurl` to read every single npm module inside of the text file `node_modules/node-libcurl/yarn.lock` and merge it into a single `npm install ...` command to be run inside the `node_modules/node-libcurl` directory.

I am not super familiar with how npm/nodejs works and I have no idea what `yarn.lock` is, but it contains a list of many modules inside it, so I thought installing everything I see could do the trick.

After installing all the modules listed in `yarn.lock` and running `npm install --save-dev electron-rebuild` inside my root folder (not inside `node_modules/node-libcurl`), I'm stuck at the following output:

```bash
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN downloader@1.0.0 No description
npm WARN downloader@1.0.0 No repository field.

npm ERR! path C:\Users\Arise\Documents\Programming\JS\Electron\downloader\node_modules\node-libcurl\node_modules\node-pre-gyp\node_modules\nopt
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Users\Arise\Documents\Programming\JS\Electron\downloader\node_modules\node-libcurl\node_modules\node-pre-gyp\node_modules\nopt' -> 'C:\Users\Arise\Documents\Programming\JS\Electron\downloader\node_modules\node-libcurl\node_modules\node-pre-gyp\node_modules\.nopt.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Arise\AppData\Roaming\npm-cache\_logs\2018-02-20T13_16_54_329Z-debug.log
```

**Comment by Acidic9** [comment]
I found my solution here: npm/npm#17444 (comment)

Just had to delete package-lock.json, then run npm install --save-dev electron-rebuild and it worked!

**Comment by Alhamou** [comment]
try this :

`apt-get install build-essential`
then:

`npm i node-libcurl `
