### ISSUE TITLE
After rebuilding sqlite3 on Electron v1.8.3, Electron become v1.4.13

### ISSUE THREAD

**Issue by Pingze-github** [electron/electron-rebuild#232]
@:
windows 7
node v8.1.3
electron v1.8.3 (latest)
npm v5.6.0

command: 
```
npm i --save electron
npm i --save sqlite3
npm i --save-dev electron-prebuilt
npm i --save-dev electron-rebuild
.\node_modules\.bin\electron-rebuild.cmd -f -w sqlite3 -v 1.8.3
```

I got a report "Rebuild Complete". Then I run my app, sqlite3 is OK, but an error currored about "async".
So I check my Electron version:
`.\node_modules\.bin\electron -v`
Got `v1.4.13`

I tried to rebuild with a certain version by `-v`, but it is useless.

**Comment by malept** [comment]
Use `electron`, not `electron-prebuilt`. See: http://electronjs.org/blog/npm-install-electron
