### ISSUE TITLE
gRPC problem in Electron

### ISSUE THREAD

**Issue by PlacidoDomingo** [electron/electron-rebuild#233]
I have a trouble when using gRPC in electron, like " var grpc = require('grpc'); " 
the error is A dynamic link DLL initialization routine failed
Anyone has the idea of how to solve this problem? 
it't ergent, Thx!

**Comment by nicolasnoble** [comment]
You shouldn't post this here - electron-rebuild doesn't really have anything to do with gRPC. The best location should be https://github.com/grpc/grpc-node. Also, electron-rebuild doesn't work properly with gRPC because gRPC uses node-pre-gyp while electron-rebuild invokes node-gyp directly.

And if you would give some more details on what you've done that gets you into that state, with for instance a test case, that'd be great.

**Comment by PlacidoDomingo** [comment]
Thank you for your replay, I'm a rookie in web development. I'll re-post it to  https://github.com/grpc/grpc-node later.
Here is the details on my test case: First I used nmp to install gRPC, then I used electron-quick-start to create a template project ,then add "var gRPC = require('gRPC');" in the head part of main.js, finally I used cmd like 'electron project_path' received the error above.

**Comment by PlacidoDomingo** [comment]
Thank you for your reply, I'm a rookie in web development. I'll re-post it to https://github.com/grpc/grpc-node later.
 Here is the details on my test case: First I used nmp to install gRPC, then I used electron-quick-start to create a template project ,then add "var gRPC = require('gRPC');" in the head part of main.js, finally I used cmd like 'electron project_path' received the error above.

**Comment by PlacidoDomingo** [comment]
Thank you for your reply, I'm a rookie in web development. I'll re-post it to https://github.com/grpc/grpc-node later.
 Here is the details on my test case: First I used nmp to install gRPC, then I used electron-quick-start to create a template project ,then add "var gRPC = require('gRPC');" in the head part of main.js, finally I ran cmd like 'electron project_path' received the error above.

**Comment by MarshallOfSound** [comment]
@PlacidoDomingo You need to install and run `electron-rebuild` for native modules to work
