### ISSUE TITLE
What's the difference between the --which-module and --only options?

### ISSUE THREAD

**Issue by aguynamedben** [electron/electron-rebuild#253]
First off, thank you SO much for publishing and maintaining this excellent tool. If I had to provide this low-level functionality myself I would be completely lost. 🙏

Using `--which-module` does what I expect, does the work to rebuild modules:
```
$ ../node_modules/.bin/electron-rebuild --which-module @sentry/electron,sequelize --parallel --force --types prod,dev,optional --module-dir .
⠴ Building modules: 0/1
✔ Rebuild Complete
```

Using `--only` shows "Rebuild Complete", but it doesn't seem to actually do the work of rebuilding the modules (I never see the "Building modules" message).
```
$ ../node_modules/.bin/electron-rebuild --only @sentry/electron,sequelize --parallel --force --types prod,dev,optional --module-dir .
✔ Rebuild Complete
```

Is `--only` "smart" in that it doesn't rebuild modules if it's not necessary? The documentation in the README for either command doesn't make it clear there is a difference between them.

About my project if it helps understand my context:
* Based on electron-react-boilerplate
* Uses the 2 package.json structure
* I want to use `--which-module` because I need to exclude `node-sqlite3` from my electron-rebuild command because I need to build `node-sqlite3` from source so that I can [use SQLCipher encryption for SQLite](https://github.com/mapbox/node-sqlite3#building-for-sqlcipher).

**Comment by MarshallOfSound** [comment]
> Uses the 2 package.json structure

This is a bad idea and is probably messing with `electron-rebuild`'s internal module resolution logic.  `electron-rebuild` was designed with a single package.json in mind so there's no need for the 2 package.json hack that people used to do 😄 

If you want more detailed logs of the decisions `electron-rebuild` makes you can run it with `DEBUG=electron*`

**Comment by aguynamedben** [comment]
Thanks for your feedback here. It really helps me get a sense of the community, packaging, and rebuilding. I think I'll close this since since the question is answered here (adding vs. setting). Again, I really appreciate your perspective, so thank you 🙏.
