### ISSUE TITLE
Unable to find electron rebuilt's version number

### ISSUE THREAD

**Issue by mikeneyens** [electron/electron-rebuild#263]
I'm getting following error:

> An unhandled error occurred inside electron-rebuild
> Unable to find electron-prebuilt's version number, either install it or specify an explicit version
> 
> Error: Unable to find electron-prebuilt's version number, either install it or specify an explicit version
>     at Object.<anonymous> (C:\Users\Mike\Desktop\pos\node_modules\electron-rebuild\lib\src\cli.js:80:19)
>     at Generator.next (<anonymous>)
>     at C:\Users\Mike\Desktop\pos\node_modules\electron-rebuild\lib\src\cli.js:8:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Mike\Desktop\pos\node_modules\electron-rebuild\lib\src\cli.js:4:12)
>     at C:\Users\Mike\Desktop\pos\node_modules\electron-rebuild\lib\src\cli.js:69:8
>     at Object.<anonymous> (C:\Users\Mike\Desktop\pos\node_modules\electron-rebuild\lib\src\cli.js:145:4)
>     at Module._compile (internal/modules/cjs/loader.js:688:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
>     at Module.load (internal/modules/cjs/loader.js:598:32)

Electron version: 3.0.9
Native module: nfc-pcsc
Rebuilt using:  .\node_modules\.bin\electron-rebuild.cmd

I tried to install electron-prebuilt. The rebuild works now, but then I get the following error: 

> The module '\\?\C:\Users\Mike\desktop\pos\node_modules\@pokusew\pcsclite\build\Release\pcsclite.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 50. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Thanks in advance for the help!

Mike

**Comment by mikeneyens** [comment]
Turns out electron was not installed as a devDependency. Electron-rebuild now works.

**Comment by agmt5989** [comment]
Not for me though
