### ISSUE TITLE
rebuild node-pty failed

### ISSUE THREAD

**Issue by gaograce** [electron/electron-rebuild#269]
When I run command as follows in node-pty(win10 system), nothing wrong:
"C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\Desktop\\Project\\MyProject\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild", but electron-rebuild node-pty failed.

node: 8.11.2
node-gyp: 3.6.2
electron: 2.0.16
electron-rebuild:1.8.2
node-pty:0.8.0
 VCTargetsPath=C:\Program Files (x86)\MSBuild\Microsoft.cpp\v4.0\v140
msvs_version=2015
python2.7

Error message:
 winpty-agent.vcxproj -> C:\Users\admin\Desktop\Project\MyProject\node_modules\node-pty\build\Release\\winpty-agent.exe
  winpty-agent.vcxproj -> C:\Users\admin\Desktop\Project\MyProject\node_modules\node-pty\build\Release\winpty-agent.pdb (Full PDB)
gyp ERR! build error
gyp ERR! stack Error: `msbuild` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\admin\Desktop\Project\MyProject\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\admin\\Desktop\\Project\\MyProject\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=2.0.16" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd C:\Users\admin\Desktop\Project\MyProject\node_modules\node-pty
gyp ERR! node -v v8.11.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\Users\admin\Desktop\Project\MyProject\node_modules\spawn-rx\lib\src\index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (C:\Users\admin\Desktop\Project\MyProject\node_modules\rxjs\Subscriber.js:242:16)
    at SafeSubscriber.error (C:\Users\admin\Desktop\Project\MyProject\node_modules\rxjs\Subscriber.js:201:26)
    at Subscriber._error (C:\Users\admin\Desktop\Project\MyProject\node_modules\rxjs\Subscriber.js:132:26)
    at Subscriber.error (C:\Users\admin\Desktop\Project\MyProject\node_modules\rxjs\Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (C:\Users\admin\Desktop\Project\MyProject\node_modules\rxjs\Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (C:\Users\admin\Desktop\Project\MyProject\node_modules\rxjs\Subscriber.js:106:18)
    at SafeSubscriber._next (C:\Users\admin\Desktop\Project\MyProject\node_modules\spawn-rx\lib\src\index.js:251:65)
    at SafeSubscriber.__tryOrSetError (C:\Users\admin\Desktop\Project\MyProject\node_modules\rxjs\Subscriber.js:251:16)
    at SafeSubscriber.next (C:\Users\admin\Desktop\Project\MyProject\node_modules\rxjs\Subscriber.js:191:27)

What happened?

**Comment by gaograce** [comment]
ps: I also rebuild deasync, grpc, no error.

**Comment by gaograce** [comment]
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.2 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\admin\\Desktop\\Project\\MyProject\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto’,
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\Desktop\\Project\\MyProject\\node_modules\\node-pty\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\Desktop\\Project\\MyProject\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\.node-gyp\\iojs-2.0.16\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\admin\\.node-gyp\\iojs-2.0.16',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\admin\\Desktop\\Project\\MyProject\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\admin\\.node-gyp\\iojs-2.0.16\\<(target_arch)\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\admin\\Desktop\\Project\\MyProject\\node_modules\\node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\admin\\Desktop\\Project\\MyProject\\node_modules\\node-pty\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]

**Comment by gaograce** [comment]
**node-gyp info：（"C:\Program Files\nodejs\node.exe" "C:\Users\admin\Desktop\Project\MyProject\node_modules\node-gyp\bin\node-gyp.js" "rebuild"）**gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@8.11.2 | win32 | x64
gyp info spawn C:\Python27\python.EXE
gyp info spawn args [ 'C:\\Users\\admin\\Desktop\\Project\\Quaty-Dog\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=auto',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\Desktop\\Project\\Quaty-Dog\\node_modules\\node-pty\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\Desktop\\Project\\Quaty-Dog\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\admin\\.node-gyp\\8.11.2\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\admin\\.node-gyp\\8.11.2',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\admin\\Desktop\\Project\\Quaty-Dog\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\admin\\.node-gyp\\8.11.2\\<(target_arch)\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\admin\\Desktop\\Project\\Quaty-Dog\\node_modules\\node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\admin\\Desktop\\Project\\Quaty-Dog\\node_modules\\node-pty\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn msbuild
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]

**Comment by monicaxun** [comment]
@gaograce Did you resolve this issue? I have encountered it the same.

**Comment by vaheqelyan** [comment]
+1

**Comment by gaograce** [comment]
> @gaograce Did you resolve this issue? I have encountered it too.

I update electron version. And rebuild successfully.
electron version: 4.0.0

**Comment by gaograce** [comment]
> @gaograce Did you resolve this issue? I have encountered it too.

I installed vs2017 and vs2015 both, so I uninstall vs2017 and set npm config set msvs_version 2015

**Comment by johndacost** [comment]
+1
