### ISSUE TITLE
target version not detected on rebuild

### ISSUE THREAD

**Issue by cdaringe** [electron/electron-rebuild#27]
hi all:

when electron-rebuild goes to rebuild assets, it complains that target version is missing.  per [this discussion](https://github.com/mapbox/node-pre-gyp/pull/175/files#r41799819), it should be populated in the latest version of electron-rebuild.

E.g.:
```
cdieringer@Snapper-osx:~/node/coinstac$ ll node_modules/ | grep electron
drwxr-xr-x  15 cdieringer  staff   510 Oct 12 13:36 electron-prebuilt/
drwxr-xr-x  10 cdieringer  staff   340 Oct 12 14:03 electron-rebuild/
```
```
cdieringer@Snapper-osx:~/node/coinstac$ cat package.json | grep electron
    "electron-prebuilt": "^0.33.7",
    "electron-rebuild": "^1.0.1",
```

however, it still yields the following, against expectation:
```
...
> fsevents@1.0.2 install /Users/cdieringer/node/coinstac/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Empty target version is not supported if electron is the target.
```

**Comment by danielmhair** [comment]
Is there a solution to this? I am getting that exact error. (I cannot add 'target=1.2.3' to my .npmrc, because it breaks npm and doesn't install anything)

**Comment by MarshallOfSound** [comment]
This issue should have been fixed with the numerous electron version detection fixes we have pushed.

Closing out
