### ISSUE TITLE
Electron rebuild fails with fs-xattr

### ISSUE THREAD

**Issue by chuyun** [electron/electron-rebuild#288]
$ npm run rebuild            

> winas@0.5.4 rebuild /Users/jun/Documents/Dev/shuwen/winas-desktop
> npx electron-rebuild

✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/node-gyp/lib/install.js:197:21)
gyp ERR! stack     at Request.emit (events.js:189:13)
gyp ERR! stack     at Request.onRequestError (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/request/request.js:881:8)
gyp ERR! stack     at ClientRequest.emit (events.js:189:13)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:392:9)
gyp ERR! stack     at TLSSocket.emit (events.js:189:13)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:82:8)
gyp ERR! stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/jun/.nvm/versions/node/v10.15.3/bin/node" "/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/.bin/node-gyp" "rebuild" "--target=4.1.0" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/fs-xattr
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1

Error: gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad 
gyp ERR! stack network settings.
gyp ERR! stack     at Request.<anonymous> (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/node-gyp/lib/install.js:197:21)
gyp ERR! stack     at Request.emit (events.js:189:13)
gyp ERR! stack     at Request.onRequestError (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/request/request.js:881:8)
gyp ERR! stack     at ClientRequest.emit (events.js:189:13)
gyp ERR! stack     at TLSSocket.socketErrorListener (_http_client.js:392:9)
gyp ERR! stack     at TLSSocket.emit (events.js:189:13)
gyp ERR! stack     at emitErrorNT (internal/streams/destroy.js:82:8)
gyp ERR! stack     at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Darwin 18.2.0
gyp ERR! command "/Users/jun/.nvm/versions/node/v10.15.3/bin/node" "/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/.bin/node-gyp" "rebuild" "--target=4.1.0" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/fs-xattr
gyp ERR! node -v v10.15.3
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

Failed with exit code: 1
    at SafeSubscriber._error (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/spawn-rx/lib/src/index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.error (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/rxjs/internal/Subscriber.js:158:26)
    at Subscriber._error (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/rxjs/internal/Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/rxjs/internal/Subscriber.js:72:18)
    at SafeSubscriber._next (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/spawn-rx/lib/src/index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (/Users/jun/Documents/Dev/shuwen/winas-desktop/node_modules/rxjs/internal/Subscriber.js:145:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 255
npm ERR! winas@0.5.4 rebuild: `npx electron-rebuild`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the winas@0.5.4 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jun/.npm/_logs/2019-03-15T07_21_03_594Z-debug.log

**Comment by malept** [comment]
This is the error:

```
gyp ERR! stack Error: This is most likely not a problem with node-gyp or the package itself and
gyp ERR! stack is related to network connectivity. In most cases you are behind a proxy or have bad
gyp ERR! stack network settings.
```
