### ISSUE TITLE
Upgrade node-abi to ^2.8.0 for Electron 5 support

### ISSUE THREAD

**Issue by Jocs** [electron/electron-rebuild#294]
When  I update Electron to v5.0.0, and error happened:

```sh
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 5.0.0 and runtime electron.  
Updating "node-abi" might help solve this issue if it is a new release of electron
```

**Comment by kirning** [comment]
I have same problem.

**Comment by abdes-zakari** [comment]
I have same problem and i change my version of electron to :

`"electron": "^4.0.2",`

and it works now

**Comment by just-push-it** [comment]
node-abi was just updated to 2.8.0 to support Electron 5.0 a few minutes ago. You can add node-abi to your dev depends manually which fixed the issue for me until they update this package.
`npm install --save-dev node-abi@2.8.0`

**Comment by malept** [comment]
I added the node-abi upgrade to #285, I'll see if I can ping someone to make a new release soon.

**Comment by malept** [comment]
FYI, you don't *need* to add `node-abi` to your dependencies/devDependencies. For Yarn, you can just run `yarn upgrade electron-rebuild`. Not sure if `npm update electron-rebuild` will do a similar thing for NPM users.

**Comment by MarshallOfSound** [comment]
For npm I believe the command is `npm upgrade node-abi --depth=100`

**Comment by adeperio** [comment]
yarn upgrade electron-rebuild did not work for me. I upgraded to electron 5.0.1

**Comment by malept** [comment]
Check your `yarn.lock` to make sure the correct `node-abi` version is installed.

**Comment by adeperio** [comment]
thanks @malept this is what I was missing
