### ISSUE TITLE
Support for electron v6.0.0

### ISSUE THREAD

**Issue by thevirajshelke** [electron/electron-rebuild#312]
I have just updated my electron version to 6.0.0. While rebuilding SQLite3 with electron-rebuild I am getting the following error.

```txt
An unhandled error occurred inside electron-rebuild
Could not detect abi for version 6.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

Error: Could not detect abi for version 6.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
```

I am able to rebuild the SQLite package using electron-builder. I am using `npx electron-builder install-app-deps`.

**Comment by MarshallOfSound** [comment]
`node-abi` has been updated 👍

**Comment by astoilkov** [comment]
New release?

**Comment by valpet** [comment]
Seems the published electron-rebuild 1.8.5 is still dependent on the previous version node-abi 2.8.0, right? May we have an update of electron-rebuild that use the latest version of node-abi, please?

**Comment by MarshallOfSound** [comment]
@valpet It depends on `^2.8.0`, the latest release of `node-abi` is `2.10.0` which is in range of that condition.  There is no need to publish a new version of `electron-rebuild`

**Comment by dperetti** [comment]
You just want to run yarn upgrade electron-rebuild.

Le ven. 2 août 2019 à 11:08, Samuel Attard <notifications@github.com> a
écrit :

**Comment by valpet** [comment]
I have not run year upgrade on that package, but used npm update instead. Still get that error message about not detecting abi for 6.0.0. I also tried wiping my node_modules folder but no improvement. I confirmed that I'm on electron-rebuild 1.8.5 and node-abi 2.8.0.

**Comment by thevirajshelke** [comment]
@valpet I think what @MarshallOfSound said is perfect. The `node-abi` package used in `electron-rebuild` has the following usage `"node-abi": "^2.8.0"`. This indicates that whenever you install electron-rebuild using either `npm` or `yarn` it should install `node-abi` v2.10.0. If this is not happening in your case you can try the following

1.
```txt
  npm update
```
Make sure you have latest npm version. (npm had some bugs updating packages in case you are using old version)

2.
```txt
  npm uninstall --save-dev electron-rebuild && npm install --save-dev electron-rebuild
```
Also are you explicitly using node-abi? (A snippet of your package.json will help)
