### ISSUE TITLE
NAPI versions not handled

### ISSUE THREAD

**Issue by truefusion** [electron/electron-rebuild#316]
https://github.com/electron/electron-rebuild/blob/90f67d9697485318a117f09f44f6b2d12e692b6f/src/rebuild.ts#L339-L344

Trying to rebuild [node-crfsuite](https://github.com/vunb/node-crfsuite) the system comes across an array for `napi_versions`, but the code expects a string, which ends up throwing a `value.replace is not a function` error.

Also, if we look at the output, we see `{node_napi_label}` is not handled.

```
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\electron\\app\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=4.2.10" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source" "--module_name=crfsuite" "--module_path=C:\\electron\\app\\node_modules\\crfsuite\\lib\\binding\\{node_napi_label}" "--package_name=crfsuite-win32-x64-{node_napi_label}.tar.gz" "--host=https://github.com/vunb/node-crfsuite/releases/download/" "--remote_path=1.0.0"
```

After messing with that command, what finally allowed me to rebuild crfsuite was to pass in the argument `--napi_build_version=3`. Of course, before providing that argument, I replaced `{node_napi_label}` with the value `napi-v3` (which is the correct label for crfsuite). Unfortunately, electron-rebuild does not consider the node module as having been rebuild, so I am unable to have it rebuild any other modules, but this is nevertheless a step in the right direction!

I hope I have provided enough information to debug and resolve this issue. I await the day that I am able to accomplish a complete electron-rebuild run!

Thank you!

**Comment by malept** [comment]
I think this might be fixed in 1.8.7. There are two N-API modules in the testsuite now.
