### ISSUE TITLE
Electron 7 & 8 Support

### ISSUE THREAD

**Issue by Stanzilla** [electron/electron-rebuild#321]
Needs to pick up https://github.com/lgeiger/node-abi/releases/tag/v2.12.0 to support the current and future Electron release

**Comment by jonmanzo** [comment]
For what it's worth, node-abi is a ^ dep, so removing and reinstalling electron-rebuild will pick up node-abi@2.12.0

**Comment by malept** [comment]
electron-rebuild does not need to be updated to pick up new `node-abi` minor versions, see https://github.com/electron/electron-rebuild/issues/294#issuecomment-486847144 and https://github.com/electron/electron-rebuild/issues/294#issuecomment-486851247 (TL;DR: run `yarn upgrade electron-rebuild` or `npm upgrade node-abi --depth=100` to upgrade `node-abi` for your project.)
