### ISSUE TITLE
Dependency on node-gyp must be updated

### ISSUE THREAD

**Issue by daniel3303** [electron/electron-rebuild#325]
It seems that electron-rebuild depends on node-gyp v5.0.1 which has a bug for macOS Catalina [https://github.com/nodejs/node-gyp/issues/1917](here). The bug has been fixed for the latest version v6.0.1. This bug prevents users from compiling some packages (not all of them), some examples are node-sqlite3, usb amoung others. 

I was able to fix the bug for me simply by updating the dependency on gyp from v5.0.1  to version v6.0.1

**Comment by zpm683** [comment]
also have this BUG:   node-gyp arm64 node.lib returns HTTP code 403  
https://github.com/nodejs/node-gyp/issues/1933

**Comment by sregger** [comment]
Delighted to see this is already in progress
