### ISSUE TITLE
Publish a new release

### ISSUE THREAD

**Issue by sregger** [electron/electron-rebuild#330]
Apologies in advance if opening an issue is not appropriate here. But I did not see any advice on how to request a publish in https://github.com/electron/electron-rebuild/blob/master/contributing.md. 

I've been trying to address an issue in our build. Namely that we can't build if we introduce a native module due to a bug in node-gyp. This bug has since been fixed in node-gyp 6.0.1 and I was delighted to see electron-rebuild had a PR to upgrade to this version of node-gyp to fix the issue. Namely

https://github.com/electron/electron-rebuild/pull/327

Now that the tests on that PR have been fixed and it is merged I'd like to request a new release of electron-rebuild to resolve the problem for those affected.

**Comment by zangornjak** [comment]
It'd be great if the new release would include the updated `"node-abi": "^2.12.0"` release to support Electron 7 and 8.

https://github.com/electron/electron-rebuild/issues/321

**Comment by Jay031** [comment]
Same question here +1 I really need to be able to rebuild Node-Keytar but it needs node-abi 2.12.0

**Comment by zangornjak** [comment]
There are probably more elegant solutions, but as a temporary fix I've cloned this repository and edited the `package.json` to use updated `node-abi`. Then `npm i` and `npm prepare`.

Afterwards I changed the `electron-rebuild` version in my `package.json` to the path of the cloned repository (`"electron-rebuild": "./tmp/electron-rebuild/"`).

**Comment by sregger** [comment]
Not sure if this is of use  to anyone. But since posting this issue I've discovered that if you use `èlectron-builder` you can avoid the need for `electron-rebuild` entirely by adding the following to package.json.

    "postinstall": "electron-builder install-app-deps",

**Comment by malept** [comment]
This is blocked by #306.

> I really need to be able to rebuild Node-Keytar but it needs node-abi 2.12.0

See https://github.com/electron/electron-rebuild/issues/321#issuecomment-553464192

**Comment by zxdong262** [comment]
If anyone really need a temp solution, this is it, only upgrade deps: `"node-abi": "^2.12.0", "node-gyp": "^6.0.1"`, I created this temp fork for my project.

```bash
# install
npm i @electerm/electron-rebuild

# run
./node_modules/.bin/electron-rebuild
```

**Comment by jcolemn3** [comment]
+1 This would be great for version 7.x. It looks like the build is failing for 1.8.6. When I install 1.8.6, the updated dependency for node-abi (2.12.0) is not pulled included. I have tried the npm update command without success. the dependency is not updated.

**Comment by zangornjak** [comment]
@jcolemn3 check out https://github.com/electron/electron-rebuild/issues/321#issuecomment-553464192 for an example of how to upgrade `node-abi`.

**Comment by malept** [comment]
1.8.7 has been released. We had some issues with our automatic release process, thanks for your patience.
