### ISSUE TITLE
Rebuild Complete, But Error 'compiled against a different Node.js version using NODE_MODULE_VERSION 72. This version of Node.js requires NODE_MODULE_VERSION 73.'

### ISSUE THREAD

**Issue by missingtears** [electron/electron-rebuild#333]
> node-pty-electron-example@1.0.0 rebuild F:\demo\examples\electron
> electron-rebuild -f -w ./node_modules/node-pty -m ./

F:\demo\examples\electron>"node"  "F:\demo\examples\electron\node_modules\.bin\\..\_electron-rebuild@1.8.6@electron-rebuild\lib\src\cli.js" -f -w ./node_modules/node-pty -m ./
√ Rebuild Complete

BUT:
Uncaught Error: Could not call remote method 'spawn'. Check that the method signature is correct. Underlying error: The module '\\?\F:\demo\examples\electron\node_modules\_node-pty@0.9.0-beta25@node-pty\build\Release\pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 72. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
Underlying stack: Error:

help me, thanks

**Comment by missingtears** [comment]
"node-pty": "0.9.0-beta25",
"electron": "^6.0.7",
"electron-rebuild": "1.8.6"
windows10

**Comment by mantou132** [comment]
some problem

**Comment by mantou132** [comment]
use `npm i --save node-pty`

**Comment by malept** [comment]
I can't reproduce this on Linux:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
# Add the following to main.js: const pty = require('node-pty')
npm install --save-dev electron-rebuild
npm install --save node-pty
node_modules/.bin/electron-rebuild
npm start
```

In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by missingtears** [comment]
![image](https://user-images.githubusercontent.com/14900353/69805114-f362a780-121a-11ea-8af5-e0c64e0affc4.png)
@malept thanks, 
Problem still
I have this problem on win10

**Comment by missingtears** [comment]
@mantou132 ，win10上的问题，你测下。

**Comment by malept** [comment]
@missingtears please provide the following or I'm going to assume that you've decided not to pursue this issue:

> In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?
