### ISSUE TITLE
electron-rebuild.cmd Failed

### ISSUE THREAD

**Issue by nbsu** [electron/electron-rebuild#341]
**I try to .\node_modules.bin\electron-rebuild.cmd, then I got error as follow.
It seems I can't download file from gh-contractor-zcbenz.s3.amazonaws.com.
How to config to use local file (node-v4.0.8-headers.tar.gz) ?**

× Rebuild Failed
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@10.11.0 | win32 | x64
gyp info find Python using Python version 2.7.14 found at "C:\Python27\python.exe"
gyp http GET https://electronjs.org/headers/v4.0.8/node-v4.0.8-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo ENOENT gh-contractor-zcbenz.s3.amazonaws.com gh-contractor-zcbenz.s3.amazonaws.com:443

gyp ERR! stack at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\WORK\mgtv\node_modules\node-gyp\bin\node-gyp.js" "rebui
ld" "--target=4.0.8" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--msvs_version=2015
"
gyp ERR! cwd C:\WORK\mgtv\node_modules\ffi
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@10.11.0 | win32 | x64
gyp info find Python using Python version 2.7.14 found at "C:\Python27\python.exe"
gyp http GET https://electronjs.org/headers/v4.0.8/node-v4.0.8-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo ENOENT gh-contractor-zcbenz.s3.amazonaws.com gh-contractor-zcbenz.s3.amazonaws.com:443

gyp ERR! stack at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\WORK\mgtv\node_modules\node-gyp\bin\node-gyp.js" "rebui
ld" "--target=4.0.8" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--msvs_version=2015
"
gyp ERR! cwd C:\WORK\mgtv\node_modules\ffi
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok

Failed with exit code: 1
at SafeSubscriber._error (C:\WORK\mgtv\node_modules\spawn-rx\lib\src\index.js:267:84)
at SafeSubscriber.__tryOrUnsub (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:205:16)
at SafeSubscriber.error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:156:26)
at Subscriber._error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:92:26)
at Subscriber.error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:72:18)
at MapSubscriber.Subscriber._error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:92:26)
at MapSubscriber.Subscriber.error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:72:18)
at SafeSubscriber._next (C:\WORK\mgtv\node_modules\spawn-rx\lib\src\index.js:242:65)
at SafeSubscriber.__tryOrUnsub (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:205:16)
at SafeSubscriber.next (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:143:22)

**Comment by malept** [comment]
```
gyp ERR! stack Error: getaddrinfo ENOENT gh-contractor-zcbenz.s3.amazonaws.com gh-contractor-zcbenz.s3.amazonaws.com:443

gyp ERR! stack at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
```

I believe this means that your DNS settings need to be fixed. This is the output when I ran `curl` on the URL, which for me works fine:

```shell
$ curl -IL https://electronjs.org/headers/v4.0.8/node-v4.0.8-headers.tar.gz
HTTP/1.1 302 Found
Server: Cowboy
Connection: keep-alive
X-Dns-Prefetch-Control: off
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains
X-Download-Options: noopen
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Set-Cookie: language=en-US; Max-Age=2592000; Path=/; Expires=Sat, 11 Jan 2020 08:19:17 GMT
Location: https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist/v4.0.8/node-v4.0.8-headers.tar.gz
Vary: Accept, Accept-Encoding
Content-Type: text/plain; charset=utf-8
Content-Length: 117
Date: Thu, 12 Dec 2019 08:19:17 GMT
Via: 1.1 vegur

HTTP/1.1 200 OK
[...]
Date: Thu, 12 Dec 2019 08:19:18 GMT
Last-Modified: Thu, 07 Mar 2019 20:39:39 GMT
ETag: "6dd2de74bd342991c55dfb5b4555dc72"
Accept-Ranges: bytes
Content-Type: application/x-tar
Content-Length: 190224
Server: AmazonS3
```

**Comment by nbsu** [comment]
How to config to use local file (node-v4.0.8-headers.tar.gz) ?

**Comment by malept** [comment]
Unfortunately, that is an option that we proxy over to `node-gyp`, it's not custom code in `electron-rebuild`.
