### ISSUE TITLE
"TypeError: rebuild is not a function" when using with electron-packager and gulp.js

### ISSUE THREAD

**Issue by MCStreetguy** [electron/electron-rebuild#345]
I came across this project today while reading the overview of the [electron-packager repo](https://github.com/electron/electron-packager#plugins) and wanted to integrate it in my build process.
As this requires to use the js api of electron-packager (according to the [README](https://github.com/electron/electron-rebuild#how-can-i-integrate-this-into-electron-packager)) I moved the shell command to my gulpfile. This seemed the most comfortable to me as I already use Gulp.js for several tasks.
I also expected this combination to work as there are sections in the README for both, the electron-packager and gulp as well.

Now whenever I want to run my build the following error occurs:
```
TypeError: rebuild is not a function
    at Object.packager.afterCopy (.../gulpfile.js:112:9)
    at internal/util.js:278:30
    at new Promise (<anonymous>)
    at Object.<anonymous> (internal/util.js:277:12)
    at .../node_modules/electron-packager/src/hooks.js:11:61
    at Array.map (<anonymous>)
    at Object.promisifyHooks (.../node_modules/electron-packager/src/hooks.js:11:29)
    at WindowsApp.copyTemplate (.../node_modules/electron-packager/src/platform.js:128:17)
    at async WindowsApp.buildApp (.../node_modules/electron-packager/src/platform.js:112:5)
    at async WindowsApp.initialize (.../node_modules/electron-packager/src/platform.js:107:7)
    at async WindowsApp.create (.../node_modules/electron-packager/src/win32.js:103:5)
    at async Promise.all (index 5)
    at async packager (.../node_modules/electron-packager/src/index.js:167:20)
    at async exports.package_app (.../gulpfile.js:77:19)
```
_(I've shortened the paths for readability. '...' is equal to my project root directory.)_

The error occurs after several minutes but I assume that this delay is related to the packaging process of electron-packager. Before that, only the usual status messages are output:
```
Packaging app for platform win32 arm64 using electron v7.1.7
Packaging app for platform linux arm64 using electron v7.1.7
Packaging app for platform linux x64 using electron v7.1.7
Packaging app for platform linux armv7l using electron v7.1.7
Packaging app for platform win32 ia32 using electron v7.1.7
Packaging app for platform linux ia32 using electron v7.1.7
Packaging app for platform win32 x64 using electron v7.1.7
Packaging app for platform darwin x64 using electron v7.1.7
Packaging app for platform mas x64 using electron v7.1.7
```

Find my gulpfile.js below for reference:
```javascript
const packager = require('electron-packager');
const rebuild = require('electron-rebuild');
const log = require('fancy-log');

// Stripped out a lot of unrelated code here in favor of readability.

exports.package_app = async (finish) => {
  const Now = new Date(),
    manifest = require('./package.json');

  let distPaths = await packager({
    all: true,
    appCopyright: ['(c)', Now.getFullYear(), manifest.author.name].join(' '),
    appVersion: manifest.version,
    asar: true,
    buildVersion: 'v' + Now.toISOString(),
    derefSymlinks: true,
    dir: process.cwd(),
    download: {
      cacheRoot: './.tmp',
      rejectUnauthorized: true,
    },
    icon: null,
    ignore: [
      '\\.editorconfig',
      '\\.gitattributes',
      '\\.gitignore',
      '\\.nvmrc',
      '\\.tmp',
      '\\.vscode',
      'config',
      'gulpfile\\.js',
      'README\\.md',
      'scripts',
      'yarn\\.lock',
    ],
    junk: true,
    out: './dist',
    overwrite: true,
    prune: true,

    // Run electron-rebuild after copying the files
    // see https://github.com/electron/electron-rebuild#how-can-i-integrate-this-into-electron-packager
    afterCopy: [
      (buildPath, electronVersion, platform, arch, callback) => {
        rebuild({ buildPath, electronVersion, arch })
          .then(() => callback())
          .catch((error) => callback(error));
      }
    ],
  });

  log('Done. Built the following packages:');
  for (const path of distPaths) {
    log(' -> ' + path);
  }

  finish();
}
```

I'm kind of confused about this error message and could not find any related information in other Issues or during my web research on the problem.
It seems as the function is not available within the callback but I can't really figure out why.
If you need any further information please let me know.

Greetings, Max

### Package Versions
- OS: macOS Mojave 10.14.6
- Node: v12.13.1
- electron: v7.1.7
- electron-packager: v14.1.1
- electron-rebuild: v1.8.8
- gulp: v4.0.2
- gulp-cli: v2.2.0

**Comment by MarshallOfSound** [comment]
`electron-rebuild` is an ES module, this is the export structure.

![image](https://user-images.githubusercontent.com/6634592/71550174-fa095800-2a2e-11ea-88bc-ae40e460ded4.png)

Your code would work if you did.

```js
const { rebuild } = require('electron-rebuild')
```

**Comment by MCStreetguy** [comment]
@MarshallOfSound I am really sorry for bothering you with such a simple mistake 🤦‍♂️
After changing the require statement as mentioned it worked perfectly.
Thanks a lot for your help!
