### ISSUE TITLE
error due to electron and electron-prebuilt both being specified in package.json

### ISSUE THREAD

**Issue by lizwxup** [electron/electron-rebuild#346]
Load electron-rebuild with electron, and the error message is as follows

electron version --2.0.4  
electron-rebuild version  --1.8.8

`.\node_modules\.bin\electron-rebuild.cmd`
`
An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@10.15.0 | win32 | ia32
gyp info find Python using Python version 2.7.15 found at "C:\Users\Administrator\.windows-build-tools\python27\python.exe"
gyp info find VS using VS2017 (15.9.28307.960) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\Administrator\.windows-build-tools\python27\python.exe
gyp info spawn args [ 'D:\\gkzZone\\terminal-collect\\node_modules\\_node-gyp@6.0.1@node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\gkzZone\\terminal-collect\\node_modules\\_ref@1.3.5@ref\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'D:\\gkzZone\\terminal-collect\\node_modules\\_node-gyp@6.0.1@node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\Administrator\\.electron-gyp\\iojs-2.0.18\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Administrator\\.electron-gyp\\iojs-2.0.18',
gyp info spawn args   '-Dnode_gyp_dir=D:\\gkzZone\\terminal-collect\\node_modules\\_node-gyp@6.0.1@node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Administrator\\\\.electron-gyp\\\\iojs-2.0.18\\\\<(target_arch)\\\\iojs.lib',
gyp info spawn args   '-Dmodule_root_dir=D:\\gkzZone\\terminal-collect\\node_modules\\_ref@1.3.5@ref',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'D:\\gkzZone\\terminal-collect\\node_modules\\_ref@1.3.5@ref\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\Microsoft Visual Stu`

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-rebuild with the environment variable `DEBUG=electron-rebuild` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by lizwxup** [comment]
i use "electron-quick-start " to start a electron project and load a "ref-wchar" types about node,it is occurs a error 
my config  package.json
`{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^7.1.7",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "electron-prebuilt": "^1.4.13",
    "electron-rebuild": "^1.8.8"
  },
  "dependencies": {}
}
`
![微信截图_20200104175834](https://user-images.githubusercontent.com/29390455/71763944-2afcf780-2f1d-11ea-9a75-8e2e33fad692.png)
 
 so, i use a official command ,"npm install --save-dev electron-rebuild  and ./node_modules/.bin/electron-rebuild"  it occurs a error 
` An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

Error: Unable to find electron's version number, either install it or specify an explicit version
    at Object.<anonymous> (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:81:19)
    at Generator.next (<anonymous>)
    at /home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:4:12)
    at /home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:70:8
    at Object.<anonymous> (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:146:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)`


i should how to  solve this error??

**Comment by lizwxup** [comment]
i use "electron-quick-start " to start a electron project and load a "ref-wchar" types about node,it is occurs a error 
my config  package.json
`{
  "name": "electron-quick-start",
  "version": "1.0.0",
  "description": "A minimal Electron application",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "repository": "https://github.com/electron/electron-quick-start",
  "keywords": [
    "Electron",
    "quick",
    "start",
    "tutorial",
    "demo"
  ],
  "author": "GitHub",
  "license": "CC0-1.0",
  "devDependencies": {
    "electron": "^7.1.7",
    "electron-debug": "^1.5.0",
    "electron-devtools-installer": "^2.2.4",
    "electron-prebuilt": "^1.4.13",
    "electron-rebuild": "^1.8.8"
  },
  "dependencies": {}
}
`
![微信截图_20200104175834](https://user-images.githubusercontent.com/29390455/71763944-2afcf780-2f1d-11ea-9a75-8e2e33fad692.png)
 
 so, i use a official command ,"npm install --save-dev electron-rebuild  and ./node_modules/.bin/electron-rebuild"  it occurs a error 
` An unhandled error occurred inside electron-rebuild
Unable to find electron's version number, either install it or specify an explicit version

Error: Unable to find electron's version number, either install it or specify an explicit version
    at Object.<anonymous> (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:81:19)
    at Generator.next (<anonymous>)
    at /home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:4:12)
    at /home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:70:8
    at Object.<anonymous> (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:146:4)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)`


i should how to  solve this error??

> i use "electron-quick-start " to start a electron project and load a "ref-wchar" types about node,it is occurs a error
> my config package.json
> `{ "name": "electron-quick-start", "version": "1.0.0", "description": "A minimal Electron application", "main": "main.js", "scripts": { "start": "electron ." }, "repository": "https://github.com/electron/electron-quick-start", "keywords": [ "Electron", "quick", "start", "tutorial", "demo" ], "author": "GitHub", "license": "CC0-1.0", "devDependencies": { "electron": "^7.1.7", "electron-debug": "^1.5.0", "electron-devtools-installer": "^2.2.4", "electron-prebuilt": "^1.4.13", "electron-rebuild": "^1.8.8" }, "dependencies": {} } `
> ![微信截图_20200104175834](https://user-images.githubusercontent.com/29390455/71763944-2afcf780-2f1d-11ea-9a75-8e2e33fad692.png)
> 
> so, i use a official command ,"npm install --save-dev electron-rebuild and ./node_modules/.bin/electron-rebuild" it occurs a error
> ` An unhandled error occurred inside electron-rebuild
> Unable to find electron's version number, either install it or specify an explicit version
> 
> Error: Unable to find electron's version number, either install it or specify an explicit version
> at Object. (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:81:19)
> at Generator.next ()
> at /home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:8:71
> at new Promise ()
> at __awaiter (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:4:12)
> at /home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:70:8
> at Object. (/home/imaboss/Downloads/electron-quick-start-master/node_modules/electron-rebuild/lib/src/cli.js:146:4)
> at Module._compile (internal/modules/cjs/loader.js:776:30)
> at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
> at Module.load (internal/modules/cjs/loader.js:653:32)`
> 
> i should how to solve this error??



> Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:
> 
> * Console output when you run electron-rebuild with the environment variable `DEBUG=electron-rebuild` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.
> * What command line arguments are you passing?
> * Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
>   problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

on windows platform

**Comment by malept** [comment]
You have both `electron` and `electron-prebuilt` specified in `package.json`. Remove `electron-prebuilt`.

Also, `ref-wchar` probably isn't compatible with Node 12 (which is used by Electron >= 5), you'll have more luck with [`ref-wchar-napi`](https://npm.im/ref-wchar-napi).
