### ISSUE TITLE
Windows 10 LNK1106 error

### ISSUE THREAD

**Issue by liulinbo123** [electron/electron-rebuild#347]
× Preparing native dependencies: 0 / 1

An unhandled error has occurred inside Forge:
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“-m”开关。
G:\CWorkSpace\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(467,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [G:\ELECTRONTEMP\electron-packager\win32-x64\message-center-win32-x64\resources\app\node_modules\websocket\build\bufferutil.vcxproj]
  bufferutil.cc
  win_delay_load_hook.cc
C:\\Users\\liulinbo\\.electron-gyp\\iojs-1.8.2-beta.5\\x64\\iojs.lib : fatal error LNK1106: 文件无效或磁盘已满: 无法查找到 0x280166 [G:\ELECTRONTEMP\electron-packager\win32-x64\message-center-win32-x64\resources\app\node_modules\websocket\build\bufferutil.vcxproj]
G:\CWorkSpace\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(467,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [G:\ELECTRONTEMP\electron-packager\win32-x64\message-center-win32-x64\resources\app\node_modules\websocket\build\validation.vcxproj]
  validation.cc
  win_delay_load_hook.cc
C:\\Users\\liulinbo\\.electron-gyp\\iojs-1.8.2-beta.5\\x64\\iojs.lib : fatal error LNK1106: 文件无效或磁盘已满: 无法查找到 0x280166 [G:\ELECTRONTEMP\electron-packager\win32-x64\message-center-win32-x64\resources\app\node_modules\websocket\build\validation.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `G:\CWorkSpace\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (G:\electron\message-center\node_modules\electron-rebuild\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "G:\\nodejs\\node.exe" "G:\\electron\\message-center\\node_modules\\electron-rebuild\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=1.8.2-beta.5" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source"
gyp ERR! cwd G:\ELECTRONTEMP\electron-packager\win32-x64\message-center-win32-x64\resources\app\node_modules\websocket
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok

**Comment by malept** [comment]
The error code LNK1106 is not an electron-rebuild specific problem. See the Microsoft docs for more information ([English](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1106?view=vs-2019), [Chinese](https://docs.microsoft.com/zh-cn/cpp/error-messages/tool-errors/linker-tools-error-lnk1106?view=vs-2019))
