### ISSUE TITLE
Unable to find electron-prebuilt's version number

### ISSUE THREAD

**Issue by MathijsvVelde** [electron/electron-rebuild#35]
![Le me at the computer](http://orig06.deviantart.net/b30f/f/2012/169/1/4/profile_picture_by_lemeplz-d5404jo.png)
```Shell
Le-me PC:app Le-me$ ./node_modules/.bin/electron-rebuild 
```
```Shell
Unable to find electron-prebuilt's version number, either install it or specify an explicit version
```
![WTF](http://hdwpics.com/images/273F33D19C1B/Angry-Meme.jpg)
![Y U NO](https://image.freepik.com/vrije-vector/yu-no-man_17-402034331.jpg)
Y U NO looking for a global installed 'electron-prebuilt' module and/or define an available version in your package.json@devDependencies!!

![I'm just saying](https://playlegit.files.wordpress.com/2013/07/im-just-saying.jpg?w=760)
Thanks!!

**Comment by paulcbetts** [comment]
Good news! There are two ways to fix this:

* Install electron-prebuilt as a dependency
* Specify the version of Electron you're using

**Comment by MathijsvVelde** [comment]
OK, some good points, BUT...
I use a lot of global modules to keep my projects clean.

I also use(d) Asar@<=0.8.2 for packaging my app, that didn't work because of the electron-prebuilt dependency, so I had to remove it...

It also works when I rebuild like this:
```Shell
./node_modules/.bin/electron-rebuild -v 0.34.3 -e /usr/local/lib/node_modules/electron-prebuilt
```

But still, Y U NO looking for the global 'electron-prebuilt' module like U do for the local one?

**Comment by zeke** [comment]
Best practice is to install `electron-prebuilt` as a devDependency so your project is portable and consistent across environments. This avoids the "works on my machine" problem.

**Comment by darkguy2008** [comment]
I'm still getting the same error when following NodeGit's guidelines for native modules here: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md . I have installed electron-prebuilt, but it says thay it has been deprecated and that electron should be used, but I already had electron, so... is it deprecated or not? what should be the new path to take?

**Comment by MarshallOfSound** [comment]
@darkguy2008 It is depreceated, you should install the `electron` module not `electron-prebuilt`

**Comment by darkguy2008** [comment]
@MarshallOfSound yeah, and that's what brought me here, because I was still seeing the same error. I'll clean up my repo and try again :/

**Comment by lazzy07** [comment]
I was trying to build opencv4nodejs and,
adding this script below and executing it did fix the problem (No need to install electron-rebuild)
"electron-rebuild": "electron-rebuild -v 5.0.4 -w opencv4nodejs",

**Comment by deepanshumehtaa** [comment]
> Best practice is to install `electron-prebuilt` as a devDependency so your project is portable and consistent across environments. This avoids the "works on my machine" problem.

Do you Mean This??
npm install --save-dev electron-rebuild

**Comment by jahbini** [comment]
npm install --save-dev electron-rebuild
Did not work.  Alas
