### ISSUE TITLE
Please support electron 8

### ISSUE THREAD

**Issue by getupp** [electron/electron-rebuild#351]
Need support for the new electron release.

**Comment by pdesantis** [comment]
To clarify, I'm getting the following error:

> An unhandled error occurred inside electron-rebuild
> Could not detect abi for version 8.0.0 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron

However, I'm on the latest `node-abi` version (2.13.0). So I think the issue is with the node-abi package https://github.com/lgeiger/node-abi/issues/77

**Comment by pdesantis** [comment]
node-abi 2.14.0 was just published, so update to that to fix this issue
https://github.com/lgeiger/node-abi/issues/77#issuecomment-582073349

**Comment by malept** [comment]
electron-rebuild does not need to be updated to pick up new `node-abi` minor versions, see [#294 (comment)](https://github.com/electron/electron-rebuild/issues/294#issuecomment-486847144) and [#294 (comment)](https://github.com/electron/electron-rebuild/issues/294#issuecomment-486851247) (TL;DR: run `yarn upgrade electron-rebuild` or `npm upgrade node-abi --depth=100` to upgrade `node-abi` for your project.)
