### ISSUE TITLE
[Question] What extra steps does electron-build take over node-gyp?

### ISSUE THREAD

**Issue by glenn2223** [electron/electron-rebuild#360]
Firstly, sorry for dropping this on an issue (don't know of any other way to ask a question on github).

**Ref: https://github.com/sass/node-sass/pull/2862**

Is there any inner workings of `electron-rebuild` that will stop me from running this
```console
node-gyp rebuild --target=8.0.0 --arch=x64 --dist-url=https://electronjs.org/headers
```

rather than this
```console
./node_modules/.bin/electron-rebuild -v=8 --arch=x64 -w node-sass
```

After doing this `npm config set msbuild_path "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe"` to suppress the VS19 folder name issue with `node-sass`'s native `node-gyp@3.8.0`

**Comment by malept** [comment]
For your use case, I would suggest [`prebuild`](https://www.npmjs.com/package/prebuild) - `electron-rebuild`'s primary use case is rebuilding native modules for Electron apps, not providing build machinery for native modules.
