### ISSUE TITLE
Users\\xxwco\\.electron-gyp\\4.0.0\\x64\\node.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x201530 [D:\workspace\ffi-demo\node_modules\ffi\build\ffi_bindings.vcxproj]

### ISSUE THREAD

**Issue by xuxuewen** [electron/electron-rebuild#361]
Users\\xxwco\\.electron-gyp\\4.0.0\\x64\\node.lib : fatal error LNK1106: �ļ���Ч���������: �޷����ҵ� 0x201530 [D:\workspace\ffi-demo\node_modules\ffi\build\ffi_bindings.vcxproj]

node -v v10.11.0
node-gyp -v 6.1.0

**Comment by malept** [comment]
This is a duplicate of #347.
