### ISSUE TITLE
Node module version mis-match with same version as electron? 

### ISSUE THREAD

**Issue by LukeWebb99** [electron/electron-rebuild#364]
I've tried making a node module that works with electron.

I've complied my module with the same version as electron as of now Electron@8.2.1 so I used Node@12.13.0 but I'm still getting the same error. how could I use electron-rebuild to fix this issue.

**Comment by malept** [comment]
The ABI numbers for Electron and Node.js are intentionally different, even though Electron may embed the same version of Node.js. Please see the README for instructions on how to use electron-rebuild.
