### ISSUE TITLE
Makes electron-rebuild source installable as a dependency

### ISSUE THREAD

**Issue by felicienfrancois** [electron/electron-rebuild#47]
On windows I can only install published release of electron-rebuild.
If I try to install from source :
```
> npm install electronjs/electron-rebuild --loglevel=info
...
npm info lifecycle asap@2.0.3~preinstall: asap@2.0.3
npm info lifecycle promise@7.1.1~preinstall: promise@7.1.1
npm info lifecycle electron-rebuild@1.0.1~preinstall: electron-rebuild@1.0.1
npm info linkStuff asap@2.0.3
npm info linkStuff promise@7.1.1
npm info linkStuff electron-rebuild@1.0.1
npm WARN ENOENT ENOENT: no such file or directory, open 'node_modules\npm-debug.log\package.json'
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electronjs/electron-rebuild" "--loglevel=info"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! path node_modules\electron-rebuild\lib\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'node_modules\electron-rebuild\lib\cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent
```

This an issue because it makes it harder to test before publishing AND it prevent to install a Fork (or the HEAD) without publishing it nor using wierd hacks.

We currently have a usecase, were some blocking issue have been reported several weeks ago, pull requests were made but the problem is not solved because it not have been merge and or published yet. As we cannot install simply a fork, we're blocked until changes are all merged AND published. 

The solution could be to add a preinstall script that check the existence of compiled files lib/*.js.
If they are missing it should install dev dependencies and compile source js.

**Comment by iarovyi** [comment]
The same thing
`D:\PROJECTS\angular2-seed-advanced>npm install electronjs/electron-rebuild --save-dev --loglevel=info
npm info it worked if it ends with ok
npm info using npm@3.10.3
npm info using node@v6.6.0
npm info git [ 'clone',
npm info git   '--template=C:\\Users\\Sergii\\AppData\\Roaming\\npm-cache\\_git-remotes\\_templates',
npm info git   '--mirror',
npm info git   'git://github.com/electronjs/electron-rebuild.git',
npm info git   'C:\\Users\\Sergii\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-electronjs-electron-rebuild-git-bb1dfca4' ]
npm info git [ 'rev-list', '-n1', 'master' ]
npm info git [ 'clone',
npm info git   'C:\\Users\\Sergii\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-github-com-electronjs-electron-rebuild-git-bb1dfca4',
npm info git   'C:\\Users\\Sergii\\AppData\\Local\\Temp\\npm-40876-e3a67799\\git-cache-a68f098a\\9b9cd61e9b86a9a9d949051b944fb65974c7fe0e' ]
npm info git [ 'checkout', '9b9cd61e9b86a9a9d949051b944fb65974c7fe0e' ]
npm info git [ 'submodule', '-q', 'update', '--init', '--recursive' ]
npm info attempt registry request try #1 at 8:48:26 AM
npm http request GET http://registry.npmjs.org/lodash
npm info attempt registry request try #1 at 8:48:26 AM
npm http request GET http://registry.npmjs.org/yargs
npm info attempt registry request try #1 at 8:48:26 AM
npm http request GET http://registry.npmjs.org/nslog
npm info attempt registry request try #1 at 8:48:26 AM
npm http request GET http://registry.npmjs.org/glob
npm http 304 http://registry.npmjs.org/glob
npm http 304 http://registry.npmjs.org/nslog
npm http 200 http://registry.npmjs.org/lodash
npm http 200 http://registry.npmjs.org/yargs
npm info attempt registry request try #1 at 8:48:27 AM
npm http request GET http://registry.npmjs.org/camelcase
npm http 304 http://registry.npmjs.org/camelcase
npm info attempt registry request try #1 at 8:48:28 AM
npm http request GET http://registry.npmjs.org/fsevents
npm http 304 http://registry.npmjs.org/fsevents
npm info lifecycle camelcase@2.1.1~preinstall: camelcase@2.1.1
npm info lifecycle glob@6.0.4~preinstall: glob@6.0.4
npm info lifecycle lodash@3.10.1~preinstall: lodash@3.10.1
npm info lifecycle yargs@3.32.0~preinstall: yargs@3.32.0
npm info lifecycle nslog@3.0.0~preinstall: nslog@3.0.0
npm info lifecycle electron-rebuild@1.2.1~preinstall: electron-rebuild@1.2.1
npm info linkStuff camelcase@2.1.1
npm info linkStuff glob@6.0.4
npm info linkStuff lodash@3.10.1
npm info linkStuff yargs@3.32.0
npm info linkStuff nslog@3.0.0
npm info linkStuff electron-rebuild@1.2.1
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/compiler-cli@0.6.3 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/core@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/common@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/compiler@2.0.1 but none was installed.
npm WARN @angular/platform-server@2.0.1 requires a peer of @angular/platform-browser@2.0.1 but none was installed.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electronjs/electron-rebuild" "--save-dev" "--loglevel=info"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! path D:\PROJECTS\angular2-seed-advanced\node_modules\electron-rebuild\lib\cli.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod

npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\PROJECTS\angular2-seed-advanced\node_modules\electron-rebuild\lib\cli.js'
npm ERR! enoent ENOENT: no such file or directory, chmod 'D:\PROJECTS\angular2-seed-advanced\node_modules\electron-rebuild\lib\cli.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     D:\PROJECTS\angular2-seed-advanced\npm-debug.log

D:\PROJECTS\angular2-seed-advanced>
`

**Comment by MarshallOfSound** [comment]
This is due to how `babel` NPM modules work.  Installing from source is not possible as we would have to make `babel` and all it's dependencies production deps which 99% of users don't want.

Closing this out as it is a technical limitation of the way `babelified` modules are published
