### ISSUE TITLE
Wrong compiled file path

### ISSUE THREAD

**Issue by Paxa** [electron/electron-rebuild#48]
How I run:

``` sh
rm -rf ./node_modules/fibers/bin
./node_modules/.bin/electron-rebuild -f
ls ./node_modules/fibers/bin
# => darwin-x64-v8-4.6
```

When I run application I got error:

```
Uncaught Error: `MY_APP/node_modules/fibers/bin/darwin-x64-v8-4.7/fibers.node` is missing. Try reinstalling `node-fibers`?
```

If I simply copy file then it works

```
cp -r node_modules/fibers/bin/darwin-x64-v8-4.6 node_modules/fibers/bin/darwin-x64-v8-4.7
```

I use node v5.4.1

**Comment by paulcbetts** [comment]
Yep, this is node-pre-gyp continuing to suck :-/

**Comment by gnail** [comment]
Try the new [-p](https://github.com/electronjs/electron-rebuild#node-pre-gyp-workaround) switch that tries to workaround node-pre-gyp bugs. It seems to work for me

**Comment by MarshallOfSound** [comment]
@Paxa Can you confirm if the `-p` flag worked for you, looking to clean up the issues section

**Comment by Paxa** [comment]
@MarshallOfSound Still same:
```
## There is an issue with `node-fibers` ##
`/Users/pavel/Sites/electron-rebuild/test_project/node_modules/fibers/bin/darwin-x64-50/fibers.node` is missing.

Try running this to fix the issue: /Users/pavel/Sites/electron-rebuild/test_project/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron /Users/pavel/Sites/electron-rebuild/test_project/node_modules/fibers/build
App threw an error during load
Error: Missing binary. See message above.
```

It seems like creating binary for wrong versino:
```
% ls node_modules/fibers/bin
darwin-x64-48
```

If I copy `darwin-x64-48` => `darwin-x64-50` then it works well

I created #114 to test replicate this case

**Comment by Paxa** [comment]
btw what kind of files `node-pre-gyp-fix.js` is trying to find? 
```js
glob(path.join(cwd, '**', 'electron-v*'));
```

It don't find anything when I compile fibers

**Comment by MarshallOfSound** [comment]
`fibers` is known to work with the new `electron-rebuild` (it was one of my test subjects)
