### ISSUE TITLE
[.\node_modules\.bin\electron-rebuild.cmd]  has a problem on windows

### ISSUE THREAD

**Issue by code1031** [electron/electron-rebuild#50]
![image](https://cloud.githubusercontent.com/assets/15321237/12699574/ed22b7fc-c7fa-11e5-8e49-1850a38d1166.png)

**Comment by havenchyk** [comment]
Just use `electron-rebuild` command in the npm scripts. 

Something like this:

```
"scripts": {
  "rebuild": "electron-rebuild -w keytar"
}
```

Can be closed.

**Comment by xdvarpunen** [comment]
@havenchyk Nope, problem looks like there is no electron-prebuilt saved into the package.json. Runs fine after ```npm install --save-dev electron-prebuilt```

**Comment by MarshallOfSound** [comment]
Issue appears to be lack of `electron` or `electron-prebuilt` installed in the users directory.  Closing out as resolved
