### ISSUE TITLE
Doesn't build on windows: without error

### ISSUE THREAD

**Issue by Phoscur** [electron/electron-rebuild#53]
I'm using the native printer module from npm to access a simple printer.

The usual "recompile all modules" does not work for me (cli and own script), it simply prints nothing.

I still manage to rebuild the module with the newest versions of nodejs, electron and node-gyp:

```
gastroprinter\node_modules\printer> node-gyp rebuild --target=0.36.7 --arch=ia32 --dist-url=https://atom.io/download/atom-shell
```

Please add some console printout if no module has been recompiled (and it didn't work) and investigate why printer can only be recompiled manually!

**Comment by iheart2code** [comment]
Yes, output of any kind would definitely be helpful.

**Comment by pabatribick** [comment]
I have the same issue. I don't get compiled my new own created addons and I don't get compiled that printer module. I've tried `--target=5.9.0` with that version, this command works, but I still get the same error: Uncaught Error: The system cannot find message text for message number 0x%1 in the message file
%2.

**Comment by lgeiger** [comment]
I have the same issue with [`zmq-prebuilt`](https://github.com/nteract/zmq-prebuilt).
Though manually running `npm rebuild zmq-prebuilt --target=1.1.3 --arch=x64 --dist-url=https://atom.io/download/atom-shell --build-from-source` works.

**Comment by MarshallOfSound** [comment]
@Phoscur Can you confirm if this is still an issue in the latest version?

**Comment by Phoscur** [comment]
@MarshallOfSound sorry my environment is currently broken, I can fix it with a new computer and try next month.

**Comment by MarshallOfSound** [comment]
The latest version has be rewritten so this should not be an issue any more
