### ISSUE TITLE
Promisify doesn't encapsulate ncp properly in node-pre-gyp-fix

### ISSUE THREAD

**Issue by gnail** [electron/electron-rebuild#56]
When using electron-rebuild to rebuild node-serialport module the output directory (e.g. `node_modules\serialport\build\Release\node-v47-win32-ia32`) would alternate between empty and correctly containing the .node file.

I did a bit of debugging and it seems to be caused by interaction between ncp and the main promise chain. When [ncp.js](https://github.com/AvianFlu/ncp/blob/master/lib/ncp.js) tries to copy into a directory with an existing .node file it will [remove the file and then copy it in](https://github.com/AvianFlu/ncp/blob/master/lib/ncp.js#L84-L111), which in turn [calls fs.unlink() with a callback](https://github.com/AvianFlu/ncp/blob/master/lib/ncp.js#L137-L144). However, the [await in node-pre-gyp-fix](https://github.com/electronjs/electron-rebuild/blob/master/src/node-pre-gyp-fix.js#L18) doesn't know about this async call and fires immediately, [causing the process to exit](https://github.com/electronjs/electron-rebuild/blob/master/src/cli.js#L116). On my machine, it'd exit after the file has been deleted but before the new file is copied in, which would give me an empty directory. Removing [process.exit()](https://github.com/electronjs/electron-rebuild/blob/master/src/cli.js#L116) fixes this bug as it allows the `fs.unlink()` callback to finish.

**Comment by paulcbetts** [comment]
This is the same as https://github.com/electron-userland/electron-packager/issues/252, I'd take a PR to replace ncp

**Comment by MarshallOfSound** [comment]
This issue should not exist in the new version of `electron-rebuild`
