### ISSUE TITLE
Running electron-rebuild deletes its own binary on Windows

### ISSUE THREAD

**Issue by Mossop** [electron/electron-rebuild#60]
I'm using electron-rebuild to rebuild sqlite3 on Windows. Somehow as part of the rebuild the node_modules/.bin/electron-rebuild gets deleted and then the build fails and you have to reinstall electron-rebuild to use it again.

See [log.txt](https://github.com/electron/electron-rebuild/files/211646/log.txt)

**Comment by muten84** [comment]
i had same issue try to update node to version 4.4.x

**Comment by Mossop** [comment]
I'm using node 5.9

**Comment by eberkund** [comment]
I have the same problem

**Comment by MarshallOfSound** [comment]
This is a known `node.js` bug that was fixed across versions I believe.  Please comment if it is still an issue on **latest** node.js
