### ISSUE TITLE
Verbose output option

### ISSUE THREAD

**Issue by anandthakker** [electron/electron-rebuild#61]
Depending on what packages it has to deal with, `electron-rebuild` sometimes takes a good long while; @paulcbetts would you be open adding a 'verbose' CLI option that shows that it's doing?

**Comment by paulcbetts** [comment]
I would take a PR to add it :)   Especially if it used the `spawn-rx` package, which would make it very easy to write output to the console incrementally

**Comment by michael-ts** [comment]
@anaisbetts I can't figure out how to use this option... is it now possible to get verbose output?
