### ISSUE TITLE
warning electron-rebuild > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

### ISSUE THREAD

**Issue by raphael10-collab** [electron/electron-rebuild#615]
Installing electron-rebuild gives this warning : 

    `warning electron-rebuild > lzma-native > node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped 
    node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
    warning electron-rebuild > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request
    /issues/3142
    warning electron-rebuild > node-gyp > request > har-validator@5.1.5: this library is no longer supported`

- O.S.: Ubuntu 18.04.4 Desktop
-node: v14.5.0

Reported the problem also in node-gyp's github page: https://github.com/nodejs/node-gyp/issues/2328

**Comment by malept** [comment]
There's nothing actionable for this module until the dependencies update their own dependencies, so I'm closing this.
