### ISSUE TITLE
DLL initialisation routine failed in Electron on Windows 10

### ISSUE THREAD

**Issue by FabianTerhorst** [electron/electron-rebuild#62]
I have tried to implement my own native module with electron, but im getting the following js error inside my console:"`Uncaught Error:DLL initialisation routine failed C:.../node`". I used npm install `NameOfMyModule `to install it. My main.js looks like this: `var NameOfMyModule = require('NameOfMyModule');`
I run `electron-rebuild.cmd` after calling npm install.

Edit: when im using nodejs the module works fine

**Comment by Sennevds** [comment]
Hi i have the same problem with msnodesqlv8. Everything works fine without electron but running with electron gives DLL initialisation routine failed error.
I've tried running electron-rebuild but still the same error

**Comment by FabianTerhorst** [comment]
https://github.com/electron/electron/issues/5370
