### ISSUE TITLE
"npm install --save-dev electron-rebuild "  Unsuccess

### ISSUE THREAD

**Issue by Xiao-Yaran** [electron/electron-rebuild#69]
system：W7 32
npm:2.15.0
node:V4.4.2
electron:v1.1.0

Masters,I am new to electron and nodejs,please help me.
When I run "npm install --save-dev electron-rebuild", install unsuccess

Partial log:
14474 error Windows_NT 6.1.7601
14475 error argv "D:\\WorkProgram\\nodejs\\node.exe" "D:\\WorkProgram\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron-rebuild"
14476 error node v4.4.2
14477 error npm  v2.15.0
14478 error code ELIFECYCLE
14479 error nslog@3.0.0 install: `node-gyp rebuild`
14479 error Exit status 1
14480 error Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
14480 error This is most likely a problem with the nslog package,
14480 error not with npm itself.
14480 error Tell the author that this fails on your system:
14480 error     node-gyp rebuild
14480 error You can get information on how to open an issue for this project with:
14480 error     npm bugs nslog
14480 error Or if that isn't available, you can get their info via:
14480 error
14480 error     npm owner ls nslog
14480 error There is likely additional logging output above.
14481 verbose exit [ 1, true ]
14482 verbose unbuild node_modules\electron-rebuild\node_modules\nslog
14483 info preuninstall nslog@3.0.0
14484 info uninstall nslog@3.0.0
14485 verbose unbuild rmStuff nslog@3.0.0 from C:\Users\Administrator\node_modules
14486 verbose unbuild rmStuff in C:\Users\Administrator\node_modules\electron-rebuild\node_modules
14487 info postuninstall nslog@3.0.0
14488 silly gentlyRm C:\Users\Administrator\node_modules\electron-rebuild\node_modules\nslog is being purged from base C:\Users\Administrator
14489 verbose gentlyRm don't care about contents; nuking C:\Users\Administrator\node_modules\electron-rebuild\node_modules\nslog
14490 silly vacuum-fs purging C:\Users\Administrator\node_modules\electron-rebuild\node_modules\nslog
14491 silly vacuum-fs quitting because other entries in C:\Users\Administrator\node_modules\electron-rebuild\node_modules
14492 verbose unbuild node_modules\electron-rebuild
14493 info preuninstall electron-rebuild@1.1.4
14494 info uninstall electron-rebuild@1.1.4
14495 verbose unbuild rmStuff electron-rebuild@1.1.4 from C:\Users\Administrator\node_modules
14496 silly gentlyRm C:\Users\Administrator\node_modules\.bin\electron-rebuild.cmd is being gently removed
14497 silly gentlyRm verifying C:\Users\Administrator is an npm working directory
14498 silly gentlyRm containing path C:\Users\Administrator is under npm's control, in C:\Users\Administrator
14499 silly gentlyRm deletion target C:\Users\Administrator\node_modules\.bin\electron-rebuild.cmd is under C:\Users\Administrator
14500 verbose gentlyRm vacuuming from C:\Users\Administrator\node_modules\.bin\electron-rebuild.cmd up to C:\Users\Administrator
14501 silly gentlyRm C:\Users\Administrator\node_modules\.bin\electron-rebuild is being gently removed
14502 silly gentlyRm verifying C:\Users\Administrator is an npm working directory
14503 silly gentlyRm containing path C:\Users\Administrator is under npm's control, in C:\Users\Administrator
14504 silly gentlyRm deletion target C:\Users\Administrator\node_modules\.bin\electron-rebuild is under C:\Users\Administrator
14505 verbose gentlyRm vacuuming from C:\Users\Administrator\node_modules\.bin\electron-rebuild up to C:\Users\Administrator
14506 info postuninstall electron-rebuild@1.1.4
14507 silly gentlyRm C:\Users\Administrator\node_modules\electron-rebuild is being purged from base C:\Users\Administrator
14508 verbose gentlyRm don't care about contents; nuking C:\Users\Administrator\node_modules\electron-rebuild
14509 silly vacuum-fs purging C:\Users\Administrator\node_modules\electron-rebuild
14510 silly vacuum-fs quitting because other entries in C:\Users\Administrator\node_modules

**Comment by ahallicks** [comment]
Do you have node-gyp installed globally? I had to manually install node-gyp with `npm install -g node-gyp` using `Run as Administrator` on the Node.js CMD.

**Comment by kcsm-lqk** [comment]
@ahallicks  Thanks for your help,I run "npm install -g node-gyp" then run "npm install --save-dev electron-rebuild" ,
I still don't have a successful installation...

**Comment by kcsm-lqk** [comment]
I re-install the node and npm,it still unsuccess.

error log:
Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。
C:\Windows\System32>npm install --save-dev electron-rebuild

nslog@3.0.0 install C:\Windows\System32\node_modules\nslog
node-gyp rebuild
C:\Windows\System32\node_modules\nslog>if not defined npm_config_node_gyp (node
"D:\WorkProgram\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild ) else (node "" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYT
HON env variable.
gyp ERR! stack at failNoPython (D:\WorkProgram\nodejs\node_modules\npm\node_
modules\node-gyp\lib\configure.js:401:14)
gyp ERR! stack at D:\WorkProgram\nodejs\node_modules\npm\node_modules\node-g
yp\lib\configure.js:356:11
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:117:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\WorkProgram\nodejs\node.exe" "D:\WorkProgram\nodejs\n
ode_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Windows\System32\node_modules\nslog
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'C:\Windows\System32\pac
kage.json'
npm WARN System32 No description
npm WARN System32 No repository field.
npm WARN System32 No README data
npm WARN System32 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\WorkProgram\nodejs\node.exe" "D:\WorkProgram\nodejs\node
_modules\npm\bin\npm-cli.js" "install" "--save-dev" "electron-rebuild"
npm ERR! node v6.2.0
npm ERR! npm v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR! npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR! C:\Windows\System32\npm-debug.log

**Comment by thomasjo** [comment]
@kcsm-lqk You haven't got a properly configured Python installation;
> gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.

Install Python 2.7, and your problem should go away. You should also close the duplicate issue you have opened on the main Electron repo (https://github.com/electron/electron/issues/5764).

**Comment by kcsm-lqk** [comment]
@thomasjo Thanks fo your help and  I'm sorry for disturbing you again . I am new to nodejs and electron.
(1) I installednode-gyp with "npm install -g node-gyp"
(2)I installedpython 2.7
C:\Users\Administrator>python
   Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (
   Intel)] on win32
   Type "help", "copyright", "credits" or "license" for more information.

Through this process I still  installation failed;
Error log:
   gyp ERR! build error
  gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
 ` failed with exit code: 1
 gyp ERR! stack     at ChildProcess.onExit (D:\WorkProgram\nodejs\node_modules\np
 m\node_modules\node-gyp\lib\build.js:276:23)
 gyp ERR! stack     at emitTwo (events.js:106:13)
 gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
 s.js:204:12)
 gyp ERR! System Windows_NT 6.1.7601
 gyp ERR! command "D:\\WorkProgram\\nodejs\\node.exe" "D:\\WorkProgram\\nodejs\\n
 ode_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
 gyp ERR! cwd C:\Users\Administrator\node_modules\mosca\node_modules\zmq
 gyp ERR! node -v v6.2.0
 gyp ERR! node-gyp -v v3.3.1
 gyp ERR! not ok
 npm WARN install:zmq@2.14.0 zmq@2.14.0 install: `node-gyp rebuild`
 npm WARN install:zmq@2.14.0 Exit status 1

 > nslog@3.0.0 install C:\Users\Administrator\node_modules\nslog
 > node-gyp rebuild


 C:\Users\Administrator\node_modules\nslog>if not defined npm_config_node_gyp (no
 de "D:\WorkProgram\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
 node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
 Building the projects in this solution one at a time. To enable parallel build,
 please add the "/m" switch.
  main.cc
  nslog_win.cc
 C:\Users\Administrator\node_modules\nan\nan.h(41): fatal error C1189: #error :
 This version of node/NAN/v8 requires a C++11 compiler [C:\Users\Administrator\
node_modules\nslog\build\nslog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\WorkProgram\nodejs\node_modules\np
m\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\WorkProgram\\nodejs\\node.exe" "D:\\WorkProgram\\nodejs\\n
ode_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\node_modules\nslog
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
C:\Users\Administrator
`-- (empty)

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\
package.json'
npm WARN Administrator No description
npm WARN Administrator No repository field.
npm WARN Administrator No README data
npm WARN Administrator No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\WorkProgram\\nodejs\\node.exe" "D:\\WorkProgram\\nodejs\\node
_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron-rebuild"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log
npm ERR! code 1

**Comment by thomasjo** [comment]
Seems like you don't have a C++ compiler that supports C++11
> C:\Users\Administrator\node_modules\nan\nan.h(41): fatal error C1189: #error :This version of node/NAN/v8 requires a C++11 compiler 

Install VS2015, then try again.
https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by ahallicks** [comment]
You don't need to install the full VS2015. You should be fine with just the build tools https://www.microsoft.com/en-us/download/details.aspx?id=48159

**Comment by kcsm-lqk** [comment]
@thomasjo , @ahallicks   ,  I'm sorry for disturbing you again . Do I have to install node-gyp before installing electron-rebuild?
If I have to install node-gyp.must I need to install:
  [https://github.com/nodejs/node-gyp](url)
  On Windows:
    Visual C++ Build Environment:
    Option 1: Install Visual C++ Build Tools using the Default Install option.
   Option 2: Install Visual Studio 2015 (or modify an existing installation) and select Common Tools
   for Visual C++ during setup. This also works with the free Community and Express for Desktop         editions.
  :bulb: [Windows Vista / 7 only] requires .NET Framework 4.5.1
  Install Python 2.7 (v3.x.x is not supported), and run npm config set python python2.7 (or see below        for further instructions on specifying the proper Python version and path.)
  Launch cmd,  npm config set msvs_version 2015
  If the above steps didn't work for you, please visit Microsoft's Node.js Guidelines for Windows for       additional tips.
------------------------------------------------------------------------------------------------------------------------------

Until now ,I have  installed python 2.7, installed node-gyp with "npm install -g node-gyp" , installed
BuildTools_Full_2015 .When I run "npm install --save-dev electron-rebuild " ,it still error

Microsoft Windows [版本 6.1.7601]
版权所有 (c) 2009 Microsoft Corporation。保留所有权利。
C:\Users\Administrator>npm install --save-dev electron-rebuild
> nslog@3.0.0 install C:\Users\Administrator\node_modules\nslog
> node-gyp rebuild
C:\Users\Administrator\node_modules\nslog>if not defined npm_config_node_gyp (no
de "D:\WorkProgram\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\
node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
C:\Users\Administrator\node_modules\nslog\build\nslog.vcxproj(19,3): error MSB4
019: 未找到导入的项目“C:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中
的路径正确，且磁盘上存在该文件。
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files\MSBuild\14.0\bin\msbuild.exe` failed wit
h exit code: 1
gyp ERR! stack     at ChildProcess.onExit (D:\WorkProgram\nodejs\node_modules\np
m\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:204:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "D:\\WorkProgram\\nodejs\\node.exe" "D:\\WorkProgram\\nodejs\\n
ode_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\node_modules\nslog
gyp ERR! node -v v6.2.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
C:\Users\Administrator
`-- node-gyp@3.3.1

npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Administrator\
package.json'
npm WARN Administrator No description
npm WARN Administrator No repository field.
npm WARN Administrator No README data
npm WARN Administrator No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\WorkProgram\\nodejs\\node.exe" "D:\\WorkProgram\\nodejs\\node
_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron-rebuild"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Administrator\npm-debug.log

**Comment by eugirdor** [comment]
I believe I am having a similar issue installing on Windows 10
node: 5.1.1
npm: 3.3.12
python: 2.7.11
msbuild: 14.0.25123.0

```
C:\test>npm install --save-dev electron-rebuild

> nslog@3.0.0 install C:\test\node_modules\nslog
> node-gyp rebuild


C:\test\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\nvm\v5.1.1\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. I
nstall the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\t
est\node_modules\nslog\build\nslog.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\nvm\v5.1.1\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\nvm\\v5.1.1\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\test\node_modules\nslog
gyp ERR! node -v v5.1.1
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
C:\test
├─┬ babel-runtime@5.8.38
│ └── core-js@1.2.6
├─┬ glob@6.0.4
│ ├─┬ inflight@1.0.5
│ │ └── wrappy@1.0.2
│ ├── inherits@2.0.1
│ ├─┬ minimatch@3.0.0
│ │ └─┬ brace-expansion@1.1.4
│ │   ├── balanced-match@0.4.1
│ │   └── concat-map@0.0.1
│ ├── once@1.3.3
│ └── path-is-absolute@1.0.0
├── lodash@3.10.1
├── ncp@2.0.0
├─┬ npm@3.9.5
│ ├── ansi-regex@2.0.0
│ ├─┬ fstream-npm@1.1.0
│ │ └─┬ fstream-ignore@1.0.5
│ │   └─┬ minimatch@3.0.0
│ │     └─┬ brace-expansion@1.1.4
│ │       ├── balanced-match@0.4.1
│ │       └── concat-map@0.0.1
│ ├─┬ glob@7.0.3
│ │ ├─┬ minimatch@3.0.0
│ │ │ └─┬ brace-expansion@1.1.3
│ │ │   └── concat-map@0.0.1
│ │ └── path-is-absolute@1.0.0
│ ├── inflight@1.0.5
│ ├── inherits@2.0.1
│ ├─┬ init-package-json@1.9.4
│ │ └─┬ glob@6.0.4
│ │   ├─┬ minimatch@3.0.0
│ │   │ └─┬ brace-expansion@1.1.4
│ │   │   ├── balanced-match@0.4.1
│ │   │   └── concat-map@0.0.1
│ │   └── path-is-absolute@1.0.0
│ ├─┬ node-gyp@3.3.1
│ │ └─┬ glob@4.5.3
│ │   └─┬ minimatch@2.0.10
│ │     └─┬ brace-expansion@1.1.3
│ │       └── concat-map@0.0.1
│ ├── once@1.3.3
│ ├─┬ read-package-json@2.0.4
│ │ └─┬ glob@6.0.4
│ │   ├─┬ minimatch@3.0.0
│ │   │ └─┬ brace-expansion@1.1.3
│ │   │   └── concat-map@0.0.1
│ │   └── path-is-absolute@1.0.0
│ ├── rimraf@2.5.2
│ └── strip-ansi@3.0.1
├─┬ promise@7.1.1
│ └── asap@2.0.4
├─┬ rimraf@2.5.2
│ └── glob@7.0.3
└─┬ yargs@3.32.0
  ├── camelcase@2.1.1
  ├─┬ cliui@3.2.0
  │ ├─┬ strip-ansi@3.0.1
  │ │ └── ansi-regex@2.0.0
  │ └── wrap-ansi@2.0.0
  ├── decamelize@1.2.0
  ├─┬ os-locale@1.4.0
  │ └─┬ lcid@1.0.0
  │   └── invert-kv@1.0.0
  ├─┬ string-width@1.0.1
  │ ├─┬ code-point-at@1.0.0
  │ │ └── number-is-nan@1.0.0
  │ └── is-fullwidth-code-point@1.0.0
  ├── window-size@0.1.4
  └── y18n@3.2.1

npm WARN ENOENT ENOENT: no such file or directory, open 'C:\test\package.json'
npm WARN EPACKAGEJSON test No description
npm WARN EPACKAGEJSON test No repository field.
npm WARN EPACKAGEJSON test No README data
npm WARN EPACKAGEJSON test No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron-rebuild"
npm ERR! node v5.1.1
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\test\npm-debug.log

C:\test>
```

**Comment by Xiao-Yaran** [comment]
Thanks all, I have solved my problem. Following these steps  [https://github.com/nodejs/node-gyp] , and  
I can install  electron-rebuild successfully!!

**Comment by iridescent-rsy** [comment]
@Xiao-Yaran 
Hi, Xiao:
I have got the same problem as yours but finally you got it resolved.
The error message is shown as this:
```
PS D:\Coder'sCode\node.js\electron\data_analyser> npm install --save-dev electron-rebuild
npm WARN prefer global npm@3.10.6 should be installed with -g

> nslog@3.0.0 install D:\Coder'sCode\node.js\electron\data_analyser\node_modules\nslog
> node-gyp rebuild

D:\Coder'sCode\node.js\electron\data_analyser\node_modules\nslog>if not defined npm_config_node_gyp (node "C:\Program Fi
les\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebu
ild )
在此解决方案中一次生成一个项目。若要启用并行生成，请添加“/m”开关。
D:\Coder'sCode\node.js\electron\data_analyser\node_modules\nslog\build\nslog.vcxproj(20,3): error MSB4019: 未找到导入的
项目“D:\
Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:2
76:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14905
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node
-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Coder'sCode\node.js\electron\data_analyser\node_modules\nslog
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
electron-quick-start@1.0.0 D:\Coder'sCode\node.js\electron\data_analyser
+-- babel-runtime@5.8.38  extraneous
+-- glob@6.0.4  extraneous
+-- lodash@3.10.1  extraneous
+-- ncp@2.0.0  extraneous
+-- npm@3.10.6  extraneous
+-- promise@7.1.1  extraneous
+-- rimraf@2.5.4  extraneous
`-- yargs@3.32.0  extraneous

npm ERR! Windows_NT 10.0.14905
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "ins
tall" "--save-dev" "electron-rebuild"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Coder'sCode\node.js\electron\data_analyser\npm-debug.log
```
I have build tool and node-gyp installed already. Could you please show me that how you finally figure out this problem? Thanks.

**Comment by gjavi1** [comment]
@iridescent-rsy installing electron-rebuild globally solved the problem for me 

```
npm install -g electron-rebuild
```

**Comment by iridescent-rsy** [comment]
@gjavi1 Thanks for reply!
I tried to add `-g` but it still got an error.... It shows a red error message like this:
```C:\Users\xxx\AppData\Roaming\npm\node_modules\electron-rebuild\node_modules\nslog\build\nslog.vcxproj(20,3): error MSB4
019: 未找到导入的项目“C:\Microsoft.Cpp.Default.props”。请确认 <Import> 声明中的路径正确，且磁盘上存在该文件。````
It seems that something is missing but I don't know how to solve this. Do you have any idea? :eyes:

**Comment by gjavi1** [comment]
@iridescent-rsy is [Visual C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools) installed on your machine?

**Comment by iridescent-rsy** [comment]
@gjavi1 I have installed it. Maybe the msbuild was not installed correctly. I tried another command to install the develop-environment : `npm install -g windows-build-tools`. And it can solve the problem. Thanks a lot! 😄

**Comment by ahallicks** [comment]
Also, try setting a specific version for msvs of you do have the build tools installed. I have had to use `--msvs_version=2013` and `--msvs_version=2015` to get things working in the past.

**Comment by iridescent-rsy** [comment]
@ahallicks Thanks. I have solved this problem. I believe the version of msbuild is the key.

**Comment by MarshallOfSound** [comment]
So I've kind of been following this thread for the last few hours and reading through it looks like everyone has solved there problems in various ways.

I'll close this out now as everything looks good from here 👍

**Comment by woodev01** [comment]
I'm sorry to reopen this, but I am having the same or a very similar problem and the help already in this thread has not fixed it. I have re-installed node and npm. I have all the Visual studio build tools installed. I have run this in Administrator: CMD and in Windows 7.1 SDK command prompt, to no avail. I have installed node-gyp globally, as well as node and npm. I don't know what else I can do. 

Log: 

gyp ERR! build error
gyp ERR! stack Error: 'C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe' failed with exit code: 2148734720
gyp ERR! stack at ChildProcess.onExit (C:\Users\path\to\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13:)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! Command "C:\\Program Files\\nodejs\\node.exe" "C:\\Path\\To\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron-rebuild""
gyp ERR! cwd C:\Path\to\Project\node_modules\nslog
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN Project@1.0.0 No description
npm WARN Project@1.0.0 No repository field.
npm WARN Project@1.0.0 No license field.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Path\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--save-dev" "electron-rebuild"
npm ERR! node v6.6.0
npm ERR! npm v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! nslog@3.0.0 install: 'node-gyp rebuild'
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nslog package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nslog
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nslog
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Path\To\Project\npm-debug.log

**Comment by Steviey** [comment]
+1

**Comment by krisscox** [comment]
Same issue here

**Comment by AjOpon** [comment]
+1

**Comment by loomismeister** [comment]
Hey all, I managed to solve this problem after a few nights of trying everything in this thread and elsewhere.

Currently I'm on a windows 10 PC and was getting all of these posted error logs.

My belief is that there was a install script bug related to paths, but I can't be sure.

The fix: 
Clone or download the nslog repo, 
copy it into your node_modules renamed to just nslog,
run ```node-gyp configure```, which looks at the binding.gyp file.
run ```node-gyp rebuild```

Now you should be able to do the npm install electron-rebuild as it now has that nslog dependency solved.

**Comment by Tanjh1996** [comment]
@iridescent-rsy  请问是不是 npm install --global --production windows-build-tools就能解决了
