### ISSUE TITLE
.\node_modules\.bin\electron-rebuild.cmd on windows 10 - no build

### ISSUE THREAD

**Issue by robinne** [electron/electron-rebuild#71]
I have gotten electron-rebuild to work on one Windows 7 machine after many errors regarding visual studio being installed and then it not being able to find the correct version. I resolved it and was able to build sqlite3 for electron.

Now I am on a Windows 10 and I am not getting any errors, but also, no rebuild is occurring. I know that when this works, my sqlite3 will build and be available for electron. 

Current behavior on Windows 10 is that the command prompt returns, no errors, no build. like so:

rootwebdir>.\node_modules\.bin\electron-rebuild.cmd
rootwebdir>

How do I debug this? Thanks.

**Comment by JouzaLoL** [comment]
Also having this issue, it's really frustrating. I can't get the modules to rebuild any other way also.

**Comment by paulcbetts** [comment]
Set the DEBUG environment variable to "*,-babel"

**Comment by dougludlow** [comment]
Same here on OS X running `./node_modules/.bin/electron-rebuild`.

**Comment by paulcbetts** [comment]
This is because node-pre-gyp breaks rebuild, `git clean -xdf` and rebuild it
