### ISSUE TITLE
node_api.h' file not found

### ISSUE THREAD

**Issue by Yongle-Fu** [electron/electron-rebuild#712]
```node_modules/node-addon-api/napi.h:4:10: fatal error: 'node_api.h' file not found```

```node-gyp build```  had same issue
but ```node-gyp rebuild``` is ok

electron-rebuild: 2.3.5 on Mac & Windows

**Comment by malept** [comment]
There's not enough information here to determine what's going on. Please provide a list of steps to reproduce this error reliably, including which native module you're trying to rebuild. If we get that, we can consider re-opening this issue.

**Comment by Yongle-Fu** [comment]
https://github.com/tessel/node-usb/issues/439

**Comment by Yongle-Fu** [comment]
https://github.com/Yongle-Fu/electron_rebuild_test
