### ISSUE TITLE
Electron rebuild didn't work with node-serialport and Raspberry PI

### ISSUE THREAD

**Issue by meron1122** [electron/electron-rebuild#74]
Console log:

> pi@raspberrypi ~/rfid/electronApp % ./node_modules/.bin/electron-rebuild -f -p -m node_modules 

>./node_modules/.bin/electron-rebuild -f -p -m node_modules  45.88s user 3.34s system 100% cpu 49.079 total

Project structure and package.json

![zrzut ekranu z 2016-05-30 15 19 50](https://cloud.githubusercontent.com/assets/2895090/15650616/2698a806-267a-11e6-98b6-0d3cf000565a.png)

I want rebuild node-serialport, because if i run electron app, they says me "Module version mismatch" on serialport module.

How i can solve this?

**Comment by paulcbetts** [comment]
I don't think electron-rebuild properly supports ARM at the moment :(

**Comment by meron1122** [comment]
Oh, well....
So, how to rebuild manual module for electron?

**Comment by meron1122** [comment]
Solved by:
`cd node_modules/serialport && node-gyp rebuild --target=1.2.0 --dist-url=https://atom.io/download/atom-shell
`

**Comment by meron1122** [comment]
You won't fix script?:)
