### ISSUE TITLE
parameters? documentation?

### ISSUE THREAD

**Issue by Janneman84** [electron/electron-rebuild#77]
I'm trying to use electron-rebuild in the cli, but how am I supposed to find out what its usage parameters are? The readme doesn't mention these at all and is just too minimal to be really useful if you ask me.

It took me a lot of time and frustration to find out how this works. Why does the readme only explain how to install it and not how to actually use it (including various examples)?

(above applies not just to electron-rebuild, but to the vast majority of what you can find here on Github, super frustrating...)

**Comment by dreambottle** [comment]
I'm joining this request. This is an important thing to do, and it is not so hard to add the section into the readme.

Meanwhile, I recommend everyone to use the -h option to list all other options in the console. This option is also nowhere to be seen BTW, I found it while looking into the sources.

**Comment by MarshallOfSound** [comment]
The options are now documented in the README
