### ISSUE TITLE
Current release 1.1.4 or 1.1.5?

### ISSUE THREAD

**Issue by eugirdor** [electron/electron-rebuild#79]
There is a [1.1.5](https://github.com/electron/electron-rebuild/releases/tag/1.1.5) release available but package.json has the version listed as [1.1.4](https://github.com/electron/electron-rebuild/blob/d87d464030523ac175f8635c9ea9639a97bb749b/package.json#L3).

**Comment by MarshallOfSound** [comment]
Updated in #102
