### ISSUE TITLE
electron-rebuild usb error

### ISSUE THREAD

**Issue by Yongle-Fu** [electron/electron-rebuild#806]
https://github.com/tessel/node-usb/issues/439
https://github.com/Yongle-Fu/electron_rebuild_test

need help

**Comment by malept** [comment]
Works for me on Linux. The linked bug indicates that it works on macOS.

If you need assistance with using electron-rebuild or the native module, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).
