### ISSUE TITLE
Rebuild fails on Windows with NSLOG error

### ISSUE THREAD

**Issue by kgentes** [electron/electron-rebuild#81]
Every time I rebuild against electron,  the following error is occurring in the command line output:

> gyp ERR! clean error
> gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\git\translation-utility\node_modules\nslog\build\Release\nslog.node'
> gyp ERR! stack     at Error (native)
> gyp ERR! System Windows_NT 6.1.7601
> gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\git\\translation-utility\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
> gyp ERR! cwd C:\git\translation-utility\node_modules\nslog
> gyp ERR! node -v v6.2.2
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> 
> npm ERR! Windows_NT 6.1.7601
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\git\\translation-utility\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.2.6" "--arch=x64"
> npm ERR! node v6.2.2
> npm ERR! npm  v3.10.3
> npm ERR! code ELIFECYCLE
> npm ERR! nslog@3.0.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR!
> npm ERR! Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
> npm ERR! Make sure you have the latest version of node.js and npm installed.
> npm ERR! If you do, this is most likely a problem with the nslog package,
> npm ERR! not with npm itself.
> npm ERR! Tell the author that this fails on your system:
> npm ERR!     node-gyp rebuild
> npm ERR! You can get information on how to open an issue for this project with:
> npm ERR!     npm bugs nslog
> npm ERR! Or if that isn't available, you can get their info via:
> npm ERR!     npm owner ls nslog
> npm ERR! There is likely additional logging output above.
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     C:\git\translation-utility\node_modules\npm-debug.log

Additionally, here is the log file that shows the error as 

> 12882 verbose rebuildBundles nslog@3.0.0
> 12883 info lifecycle nslog@3.0.0~install: nslog@3.0.0
> 12884 verbose lifecycle nslog@3.0.0~install: unsafe-perm in lifecycle true
> 12885 verbose lifecycle nslog@3.0.0~install: PATH: C:\git\translation-utility\node_modules\npm\bin\node-gyp-bin;C:\git\translation-utility\node_modules\nslog\node_modules\.bin;C:\git\translation-utility\node_modules\.bin;C:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\IBM\RationalSDLC\common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\IBM\RationalSDLC\ClearCase\bin;C:\Program Files (x86)\IBM\gsk8\lib;C:\Program Files (x86)\IBM\gsk8\bin;C:\Program Files (x86)\Collaborator Client;C:\Program Files (x86)\Common Files\Rockwell\;C:\Program Files (x86)\Rockwell Software\RSCommon;C:\Program Files (x86)\Rockwell Automation\BatchVersion;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Users\jediuser\AppData\Roaming\npm
> 12886 verbose lifecycle nslog@3.0.0~install: CWD: C:\git\translation-utility\node_modules\nslog
> 12887 silly lifecycle nslog@3.0.0~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
> 12888 silly lifecycle nslog@3.0.0~install: Returned: code: 1  signal: null
> 12889 info lifecycle nslog@3.0.0~install: Failed to exec install script
> 12890 verbose stack Error: nslog@3.0.0 install: `node-gyp rebuild`
> 12890 verbose stack Exit status 1
> 12890 verbose stack     at EventEmitter.<anonymous> (C:\git\translation-utility\node_modules\npm\lib\utils\lifecycle.js:242:16)
> 12890 verbose stack     at emitTwo (events.js:106:13)
> 12890 verbose stack     at EventEmitter.emit (events.js:191:7)
> 12890 verbose stack     at ChildProcess.<anonymous> (C:\git\translation-utility\node_modules\npm\lib\utils\spawn.js:40:14)
> 12890 verbose stack     at emitTwo (events.js:106:13)
> 12890 verbose stack     at ChildProcess.emit (events.js:191:7)
> 12890 verbose stack     at maybeClose (internal/child_process.js:852:16)
> 12890 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
> 12891 verbose pkgid nslog@3.0.0
> 12892 verbose cwd C:\git\translation-utility\node_modules
> 12893 error Windows_NT 6.1.7601
> 12894 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\git\\translation-utility\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "--runtime=electron" "--target=1.2.6" "--arch=x64"
> 12895 error node v6.2.2
> 12896 error npm  v3.10.3
> 12897 error code ELIFECYCLE
> 12898 error nslog@3.0.0 install: `node-gyp rebuild`
> 12898 error Exit status 1
> 12899 error Failed at the nslog@3.0.0 install script 'node-gyp rebuild'.
> 12899 error Make sure you have the latest version of node.js and npm installed.
> 12899 error If you do, this is most likely a problem with the nslog package,
> 12899 error not with npm itself.
> 12899 error Tell the author that this fails on your system:
> 12899 error     node-gyp rebuild
> 12899 error You can get information on how to open an issue for this project with:
> 12899 error     npm bugs nslog
> 12899 error Or if that isn't available, you can get their info via:
> 12899 error     npm owner ls nslog
> 12899 error There is likely additional logging output above.
> 12900 verbose exit [ 1, true ]
>

**Comment by paulcbetts** [comment]
Reboot then run `git clean -xdf`

**Comment by kgentes** [comment]
git clean was tried several times before. I did it again on your reply, but it doesn't solve the problem. The file clean appears to be happening after the nslog install and it fails, not before when a problematic file is already there.

This isn't just my machine, this happens on every Windows system I've seen (4 other nodes here locally). 

Issue is not resolved.

**Comment by eberkund** [comment]
I have the same issue

**Comment by sandym** [comment]
Same here. So this is closed, what's the fix ?

**Comment by kgentes** [comment]
No fix was done.. I couldn't get anyone to respond with either a resolution
or clarity if it was a problem with this or another package.

I did find out that the issue is that this process creates a file in this
format:

.ersrc.

Which isn't a valid filename in windows. It can't be deleted unless you get
it's shortname first (dir /x) ...  then you can delete it with command line
del.

Still, the process should not be creating illegal filenames in Windows..
On Jul 18, 2016 7:44 PM, "Sandy Martel" <notifications@github.com> wrote:

Same here. So this is closed, what's the fix ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/electron/electron-rebuild/issues/81#issuecomment-233515850>,
or mute the thread

**Comment by sandym** [comment]
Yeah, this might be another package bug. I fixed my build by deleting nslog.node each time before calling electron-rebuild.cmd.

`fs.unlink( 'node_modules\nslog\build\Release\nslog.node' );`

**Comment by kritollm** [comment]
You can also install Visual Studio 2013 or 2015 and  select Common Tools for Visual C++ during setup. I Already had VS 2015 so this fixed the problem for me [stackoverflow](http://stackoverflow.com/questions/33716369/error-trk0005-failed-to-locate-cl-exe/33716573#33716573).

**Comment by kgentes** [comment]
@kritollm  the issue of assigning the VS studio as your C++ toolset is not what this thread is about. This issue is specifically about the fact that nslog itself leaves an UN-deletable file around during its rebuild. This may be a problem associated with nslog itself, but it is not associated with the toolset association.
