### ISSUE TITLE
Could we make it so that Node.js and Electron (and other) binaries could co-exist?

### ISSUE THREAD

**Issue by cinderblock** [electron/electron-rebuild#817]
I find I'd like to package an app for both Node.js and Electron runtimes. I'm using `'serialport'` in a package that I want to have options to run as both a cli app and a gui app. I _could_ just use the Electron binary to run both, and just not run the gui, but there are other issues with that.

I could also take care of this packaging, building for each independently. But, this feels like it shouldn't be necessary. It also makes it hard to test and develop. Of course, both `.node` binaries would still need to be built...

But this got me thinking about a different way to fix the problem. The `'bindings'` package, that most natively linked packages use to find the appropriate `.node` file to actually `require()`, already supports scanning a range of paths, some of which are easily predictable.

So really the "problem" is that we build/deploy into the same place, no matter the platform:
```ts
path.join(module_root, 'build', 'Release')
```

Here, I've forced `'bindings'`' `require()` to fail by deleting the single `.node` file at `{module_root}\build\Release\bindings.node`.

If I run with Electron:
```log
Error: Could not locate the bindings file. Tried:
{module_root}\build\bindings.node
{module_root}\build\Debug\bindings.node
{module_root}\build\Release\bindings.node
{module_root}\out\Debug\bindings.node
{module_root}\Debug\bindings.node
{module_root}\out\Release\bindings.node
{module_root}\Release\bindings.node
{module_root}\build\default\bindings.node
{module_root}\compiled\14.16.0\win32\x64\bindings.node
{module_root}\addon-build\release\install-root\bindings.node
{module_root}\addon-build\debug\install-root\bindings.node
{module_root}\addon-build\default\install-root\bindings.node
{module_root}\lib\binding\node-v89-win32-x64\bindings.node
```

with Node 16:
```log
Error: Could not locate the bindings file. Tried:
{module_root}\build\bindings.node
{module_root}\build\Debug\bindings.node
{module_root}\build\Release\bindings.node
{module_root}\out\Debug\bindings.node
{module_root}\Debug\bindings.node
{module_root}\out\Release\bindings.node
{module_root}\Release\bindings.node
{module_root}\build\default\bindings.node
{module_root}\compiled\16.6.1\win32\x64\bindings.node
{module_root}\addon-build\release\install-root\bindings.node
{module_root}\addon-build\debug\install-root\bindings.node
{module_root}\addon-build\default\install-root\bindings.node
{module_root}\lib\binding\node-v93-win32-x64\bindings.node
```

If binaries were installed to here instead...
```js
path.join(module_root, 'lib', 'binding', `node-v${process.versions.modules}-${process.platform}-${process.arch}`)
```

Both binaries could co-exist.

[`'bindings'` claims this is from `node-pre-gyp`](https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L56-L57).

But doesn't this package use `node-pre-gyp` for precompiled binaries? So why aren't they placed there already?

Or maybe this is a per-package issue and not an Electron issue...

I'm curious for any thoughts on this.

**Comment by malept** [comment]
This isn't something that `electron-rebuild` can fix. There is [Node-API](https://nodejs.org/api/n-api.html) which seems like it can produce a native module for a given platform/arch combination that can run on multiple Node.js and Electron versions. So it's definitely more of a per-package issue.

**Comment by cinderblock** [comment]
Wait, Node-API binaries are compatible between Electron and Node versions? TIL. That seems like the right way forward. Why have more packages not switched to Node-API?!?
