### ISSUE TITLE
Process exited with code: 127 (npm install)

### ISSUE THREAD

**Issue by z3ntu** [electron/electron-rebuild#83]
In short: When you are compiling the application "abricotine" with the Arch Linux tool `makepkg` (to create a package for the package manager), there is some issue with electron-rebuild.
More detailed information are in this abricotine issue https://github.com/brrd/Abricotine/issues/63#issuecomment-231308863 .

npm: 3.10.5
nodejs: 6.3.0

but it happens with other versions of node/npm too.
I can provide more information if needed!

**Comment by MarshallOfSound** [comment]
Someone can correct me if I'm wrong, but I'm pretty sure in bash error code 127 is unknown command.

Looks like it can't find `node`https://github.com/electron/electron-rebuild/blob/master/src/main.js#L128

**Comment by z3ntu** [comment]
`node` is located at `/usr/bin/node` so I don't think this is actually a/the problem.

**Comment by MarshallOfSound** [comment]
Well the only other spawn is the `electronPath` spawner

https://github.com/electron/electron-rebuild/blob/8b73239df65161fdf5d981db9183b44774872637/src/cli.js#L73

**Comment by MarshallOfSound** [comment]
We don't spawn Electron anymore to get the version so closing this out 👍 

If it is still an issue (for some weird reason) please comment below 😄
