### ISSUE TITLE
Rebuilding for ia32 on a x64 machine

### ISSUE THREAD

**Issue by kgentes** [electron/electron-rebuild#84]
I am trying to make sure that I can build ia32 binaries for my project.

The last piece is this native module rebuild.  I am using gulp, and I cannot for the life of my figure out how to specify just electron version and the architecture parameter. In the "**installNodeHeaders**" function signature, the `--arch` option that can be given on the command line is listed as the 4th parameter.  I really want to just specify the electron version and just tell it the ia32 architecture, but function signature wants me to put all four parameters in. I am new to a lot of this so I might be making a lot of rookie mistakes, but I am stuck on how to set the arch value to ia without providing the 3rd parameter.

```
var eRebuild = require('electron-rebuild');

eRebuild.shouldRebuildNativeModules('./node_modules/.bin/electron.cmd')
.then(function(shouldBuild) {
    if (!shouldBuild) {
        return true;
    }

    return eRebuild.installNodeHeaders(electronVersion,'https://atom.io/download/atom-shell', ?????,'ia32')
        .then(function () {
            eRebuild.rebuildNativeModules(electronVersion, './node_modules');
        }).then(function () {
            eRebuild.preGypFixRun('./node_modules', true, './node_modules/.bin/electron.cmd');
        });
})
.catch(function(e) {
    log('Building modules didn\'t work: ' + e);
});
```

I have shown my code above (a pattern copied almost verbatim from the electron-rebuild README.md). How do I properly call the installNodeHeaders function? As I said, I really only want to specify the first and fourth parameters, as I have no idea what to put in the third that will work for rebuild of all modules.

`installNodeHeaders(electronVersion,'https://atom.io/download/atom-shell', ?????,'ia32')`

help....

**Comment by paulcbetts** [comment]
This is possible on Windows, but on Linux you're almost certainly going to have A Bad Time trying to do this.

**Comment by kgentes** [comment]
My issue/question still stands. Can you please answer this---

How do I properly call the installNodeHeaders function? As I said, I really only want to specify the first and fourth parameters, as I have no idea what to put in the third that will work for rebuild of all modules.

`installNodeHeaders(electronVersion,'https://atom.io/download/atom-shell', ?????,'ia32')`

**Comment by paulcbetts** [comment]
`headersDir` is just a place you want to put headers, you can use whatever. Just has to be a path that has an empty dir

**Comment by kgentes** [comment]
After much testing I have found that the actual installNodeHeaders does not properly update according the architecture parameter (the fourth param).  Fortunately, there is a way around this. You must simply use a combination of npm install and npm set commands to set up the node environment, from which the electron-rebuild will inherit its proper targets.

That is to say, after you git clone your project, be sure you are doing as follows, if you wish to build ia32 from a 64bit box:

install or switch to your 32bit installation of Node
[git clone your project or whatever... ]
cd to your project directory

Set the target architecture of your npm/node context
       `     npm set npm_config_arch ia32`

Download/install the arch specific electron prebuilt (if you need this)
       `     npm install --arch=ia32 electron-prebuilt -g`

Install and compile your project dependencies (arch switch here is specifically for electron)
       `     npm install --arch=ia32`

run your gulp code to rebuild (or use the command line if you'd rather)..

```
var eRebuild = require('electron-rebuild');

eRebuild.shouldRebuildNativeModules('./node_modules/.bin/electron.cmd')
.then(function(shouldBuild) {
    if (!shouldBuild) {
        return true;
    }

    return eRebuild.installNodeHeaders(electronVersion')
        .then(function () {
            eRebuild.rebuildNativeModules(electronVersion, './node_modules');
        }).then(function () {
            eRebuild.preGypFixRun('./node_modules', true, './node_modules/.bin/electron.cmd');
        });
})
.catch(function(e) {
    log('Building modules didn\'t work: ' + e);
});
```

Windows, electron, node and this electron-rebuild package all seem to conspire to make this process basically indecipherable by reading documentation, believing the APIs or seeing examples of this kind of usage anywhere. Hopefully this bit of info here will help others avoid this hornets nest of convolution..

**Comment by MarshallOfSound** [comment]
I don't see how you are struggling this much @kgentes 😆 

The arch parameter works perfectly fine for me, I have been using scripts like this

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/vendor/rebuild_ia32.sh

To rebuild 32bit modules on 64bit OS for ages now

**Comment by kgentes** [comment]
Yes. It works on the command line.

That is not what I was doing. For consistency our projects (and ability to
set variables based on various priest settings- notably package.son values
) use gulp for all our building.  Using electron-rebuild from api is where
issues arise. Which is why my thread centered on that and not the command
line usage.

**Comment by MarshallOfSound** [comment]
@kgentes My point was the CLI param works so you shouldn't have to do crazy npm config and npm install parameters to make the JS API work.

There is probably just an argument somewhere not being passed through.  Have you tried following the parameters and seeing where they don't get carried forward?

**Comment by kgentes** [comment]
@MarshallOfSound  @paulcbetts 

OK. I traced down through the code and found that the 
rebuildNativeModules is where the problem lies.
The way the function is constructed it takes 2 parameters (nodeVersion, nodeModulespath).
If you send it the 3rd parameter (headersDir) it incorrectly assigns it to another variable (something called whichModule, which looks like it is there for interpreting a recursive call as this same function resolves rebuilding each native modules in turn.

If you add the third parameter ("headersDir") or more (such as the ia32 arch switch  I wanted to send in) the function incorrectly handles parameters 3 and 4 in those cases. it looks  like the command line works because it knows how to read switches off the argument variable . But the parameters 3 and 4 on the API are not properly being read.

You can see this clearly as you debug from lines 239 to 245 on 
.\node_modules\electron-rebuild\lib\main.js

when using the API the third parameter could possibly be handled by the arguments variable that they are peeling other additional parameters off with, but in this case, "whichModule" is swallowing up the parameter for "headersDir" and "headersDir" likewise swallows up the parameter for "arch".

the only possible explanation I can give in reading the code is that the API is missing the explicit information that we need to provide and additional parameters (as the 3rd parameter) for "whichModule"... but if so, that means this method can't be used to rebuild all the modules-- only one at a time.. and the API published on the README is wrong...

**Comment by MarshallOfSound** [comment]
I don't think this issue is relevant with the new code base as all the old API functions are either noops or have been rewritten 👍

**Comment by fcastilloec** [comment]
what are the new API functions? the README still says that I can call `electron-rebuild` with the `--arch` option. It doesn't even specify which format the `arch` option uses, it could be `ia32`, `i386`,`x86`.
So, how can a rebuild a module for 32bit from a 64bit computer? I'm just trying to use it from the command-line, nothing else.

**Comment by lapagept** [comment]
I'm also searching for the options that `electron-rebuild` offers with the `--arch` switch...
