### ISSUE TITLE
electron Headers (headersDir) parameter does not work on API

### ISSUE THREAD

**Issue by kgentes** [electron/electron-rebuild#87]
I've been working through this API now for 2 weeks and it is basically undocumented  ( #77 ) and unusable ( #84 ) when it comes to Windows and building anything but the default options.

For the methods
- installNodeHeaders
- rebuildNativeModules

the third parameter (`headersDir` ) on `installNodeHeaders` function in the documented README are supposed to be the location of the electron headers for the recompile. However, this parameter MUST always be the location of the headers directory inside the actual electron-rebuild package. The `rebuildNativeModules` function will fail EVERY time if this value is not the equivalent of something like 

`var electronHeaders = path.resolve(__dirname, './node_modules/electron-rebuild/lib/headers');`

literally, nothing else will work for this parameter. Which makes it not only useless but incorrect in the README documentation.

Even worse is the `rebuildNativeModules` function which says (in the documentation on the README) that the 3rd parameter is the `headersDir` parameter as well. However, this is FALSE. The third parameter to this function MUST BE the name of the module you are trying to rebuild. You CAN leave this third parameter blank (as in '') but you MUST include it, or the function will fail badly. (leaving it blank will cause the function to simply apply the rebuild to all modules, which is what almost everyone wants most of the time) The `headersDir` parameter for the `rebuildNativeModules` function MUST be the 4th parameter, and it MUST be the same exact value as noted above. It's not assignable or configurable to anything else. If you wish to use this parameter it is required to be in that fixed location. Which again, makes it useless as a parameter.

What this means is that the BEST way to use these two commands is simply to leave off the optional parameters, since they are either incorrectly documented, useless or fail consistently.

All of this could have been avoided simply by having actual help either on the documentation or the command line.

Here is an example of an ACTUAL working usage of this API, which belies the formally documented parameter definitions (for both functions) given on the main page:

```
    var nodemods = './node_modules';
    var electronCMD = nodemods + '/.bin/electron.cmd';

    var electronHeaders = path.resolve(__dirname, nodemods + '/electron-rebuild/lib/headers');

    eRebuild.shouldRebuildNativeModules(electronCMD)
      .then(function(shouldBuild) {
          if (!shouldBuild) {
              return true;
          }

          return eRebuild.installNodeHeaders(electronVersion, 'https://atom.io/download/atom-shell', electronHeaders)
            .then(function () {
                eRebuild.rebuildNativeModules(electronVersion, nodemods, '', electronHeaders);
            }).then(function () {
                eRebuild.preGypFixRun(nodemods, true, electronCMD);
            });
      })
      .catch(function(e) {
          log('Building modules didn\'t work: ' + e);
      });
```

There are other problems with this API (the arch parameters do NOT work as well), but I will document that in another issue.

**Comment by MarshallOfSound** [comment]
The new `electron-rebuild` API should accept the headers URL correctly.

**Comment by kgentes** [comment]
@MarshallOfSound  i have looked around on this repo... I can't find any updated documentation on the API... the README only has options on the command line.. is there somewhere else the API will be posted?

**Comment by kgentes** [comment]
oh, I understand now.. the listing of options is the sequential order of the single API parameters.. the example was so simple, it didn't have most of the options...that is why I didn't understand at first..

thanks!

**Comment by MarshallOfSound** [comment]
That example is normally all you will need from now on 😆

**Comment by kgentes** [comment]
using the new version, it appears I have to use the keyword "default" in my gulp script as follows. Does this seem correct?

```
gulp.task('erebuild', ['clean-erebuild'], function () {
    var eRebuild = require('electron-rebuild');
    var process = require('process');
    var arch = process.arch;

    eRebuild.default(__dirname, electronVersion, arch)
        .then(function () {
            console.info('Electron Rebuild Successful');
            return true;
        }).catch(function(e) {
            log('Rebuilding modules against Electron didn\'t work: ' + e);
        });
});
```
