### ISSUE TITLE
Updating node-abi dependency to make electron-rebuild work with electron 15.x properly

### ISSUE THREAD

**Issue by tom2strobl** [electron/electron-rebuild#886]
As of right now, `electron-rebuild` builds for a wrong node version for me
```
Error: The module 'app/node_modules/better-sqlite3/build/Release/better_sqlite3.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 89. This version of Node.js requires
NODE_MODULE_VERSION 98. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```
because https://github.com/electron/electron-rebuild/blob/master/src/rebuild.ts#L124 gets the abi number from `node-abi` 3.0.0, whereas 3.2.0 has support for electron 15.x

Workaround for me right now is to add 
```
"resolutions": {  "**/node-abi": "^3.2.0" }
```
to the package.json, which is working and proves the case, but is dirty long-term.

**Comment by kryops** [comment]
We stumbled on this when trying to upgrade to Electron 15.

Looks like it should already be fixed in `master` via https://github.com/electron/electron-rebuild/pull/861, but not released yet - the latest release 3.2.3 still depends on `node-abi@^2.19.2`.

Would you consider publishing a new release that includes this fix? Thanks a lot! 🙂

**Comment by paulrosania** [comment]
Correction: This appears to have happened already, here: https://github.com/electron/electron-rebuild/pull/876. Just waiting on a release! 🤞🏼

**Comment by kryops** [comment]
My bad, I believe the actual fix happened in http://github.com/electron/electron-rebuild/pull/848

**Comment by jjeff** [comment]
Nudge. Are there plans for a new release?

**Comment by b3ni** [comment]
Im wating to new release.

**Comment by malept** [comment]
See https://github.com/electron/electron-rebuild/releases/tag/v3.2.4

**Comment by BlackGlory** [comment]
v3.2.5 still throwing the same error.
