### ISSUE TITLE
arch = madeUpArch doesn't produce errors

### ISSUE THREAD

**Issue by jakobrosenberg** [electron/electron-rebuild#914]
Setting `arch` to `wtf` either in the CLI or JS doesn't produce an error.

Is this by design? I'm not sure if anything I write in `arch` has any effect.

**Comment by malept** [comment]
It's used. For example: https://github.com/electron/electron-rebuild/blob/9d64870144f2ce673a04aa8e712e895a25b6fe2e/src/module-type/node-gyp.ts#L23

If you think it's not being passed to the various native module type handlers, feel free to debug `electron-rebuild` and file a more detailed ticket.
