### ISSUE TITLE
unreadable output while using electron-rebuild

### ISSUE THREAD

**Issue by gylove1994** [electron/electron-rebuild#948]
I am using the electron 13.0.0 and node.js v14.8.2
the terminal is zsh, font is SauceCodePro Nerd.
![image](https://user-images.githubusercontent.com/47300853/148669010-1f3928f1-840e-42ef-965e-ddeadade2aae.png)

**Comment by malept** [comment]
Workaround described here: https://github.com/electron-userland/electron-forge/issues/2665#issuecomment-1008225325

**Comment by danielweck** [comment]
This is a massive screw-up :(
