### ISSUE TITLE
electron-rebuild  errer

### ISSUE THREAD

**Issue by qqnp1100** [electron/electron-rebuild#95]
when i run  `./node_modules/.bin/electron-rebuild -$(electron -v)`
it's log  `Couldn't find electron-prebuilt and no --node-module-version parameter set, always rebuilding`
how to solve it? thanks!

**Comment by MarshallOfSound** [comment]
Change your command to

```bash
./node_modules/.bin/electron-rebuild -v $(electron -v)
```

https://github.com/electron/electron-rebuild/blob/master/src/cli.js#L13

**Comment by qqnp1100** [comment]
@MarshallOfSound  thanks
but run `./node_modules/.bin/electron-rebuild -v $(electron -v)`
it log ```
Couldn't find electron-prebuilt and no --node-module-version parameter set, always rebuilding
Canary file 'common.gypi' doesn't exist
```

**Comment by qqnp1100** [comment]
run : `sudo npm rebuild --runtime=electron --target=1.3.3 --disturl=https://atom.io/download/atom-shell --build-from-source` 
now it's ok
