### ISSUE TITLE
Export a function compatible with electron-packager afterCopy hook

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron-rebuild#99]
I recently PR'ed into `electron-packager` to add a hook to their API that will run custom functions once it has successfully copied your app files to a temp folder.

https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#aftercopy

I want to make a function that will receive the params from that hook call and rebuild the node modules in that temporary folder so that the node modules in your actual directory remain untouched

**Comment by malept** [comment]
Per https://github.com/electron/electron-rebuild/pull/120#issuecomment-270019328 I think this can be closed 😄
